"""
Generate VarMon registry init files from plc_var_registry.json.

Splits output into one ACTION file per subsystem to keep individual files small.
The dispatcher VarMon_RegInit.st just calls each subsystem action in sequence.

Usage:
    python plc_var_codegen.py [options]

    --registry   path to plc_var_registry.json  (default: plc_var_registry.json)
    --outdir     output folder                  (default: plc_code/VarMonitor)
    --max        max total variables            (default: 2000)
    --per-sub    max variables per subsystem    (default: 300)
    --skip       comma-separated prefixes to skip (default: Hardware,MAIN)
    --include    comma-separated prefixes to include (default: all except skip list)

Example — include only Exit and WHS subsystems:
    python plc_var_codegen.py --include gExitCtrl,gWHS_Ctrl

Output files:
    VarMon_RegInit.st               — dispatcher (calls each subsystem action)
    VarMon_RegInit_<Subsystem>.st   — one file per subsystem, added to IEC.prg
"""

import json
import argparse
import re
from pathlib import Path
from collections import defaultdict

# Map PLC types to (type_code, data_size)
TYPE_MAP = {
    "BOOL":   (0, 1),
    "INT":    (1, 2),
    "UINT":   (2, 2),
    "DINT":   (3, 4),
    "UDINT":  (4, 4),
    "REAL":   (5, 4),
    "LREAL":  (6, 8),
    "STRING": (7, 0),
    "USINT":  (8, 1),
    "SINT":   (9, 1),
}

# Prefixes that are low-level hardware or internal — skip by default
DEFAULT_SKIP = {"Hardware", "MAIN"}

SUBSYSTEM_HEADER = """\
(********************************************************************
 * VarMon Registry — {subsystem} subsystem
 * AUTO-GENERATED by plc_var_codegen.py — DO NOT EDIT MANUALLY
 * Variables: {count}  |  Start index: {start_idx}
 ********************************************************************)
ACTION VarMon_RegInit_{subsystem}:
"""

ENTRY_TEMPLATE = "    vmRegistry[{idx}].pAddress := ADR({name});\n" \
                 "    vmRegistry[{idx}].typeCode := {type_code};  (* {type_name} *)\n" \
                 "    vmRegistry[{idx}].dataSize := {data_size};\n"

SUBSYSTEM_FOOTER = "END_ACTION\n"

DISPATCHER_HEADER = """\
(********************************************************************
 * VarMon Registry Init — DISPATCHER
 * AUTO-GENERATED by plc_var_codegen.py — DO NOT EDIT MANUALLY
 * Total variables: {total}  |  Subsystems: {num_subs}
 ********************************************************************)
ACTION VarMon_RegInit:
    vmRegCount := 0;
"""

DISPATCHER_FOOTER = "    vmRegCount := {total};\nEND_ACTION\n"


def safe_name(prefix: str) -> str:
    """Make prefix safe as an ST action name suffix, preserving original case."""
    # Replace non-alphanumeric with underscore, then title-case first char only
    # to avoid case-collision between e.g. 'csDriveStatus' and 'CSDriveStatus'
    s = re.sub(r'[^A-Za-z0-9]', '_', prefix)
    # Normalize: uppercase first letter only (avoids CS vs cs collision)
    return s[0].upper() + s[1:] if s else s


def generate(registry_path: str, outdir: str, max_vars: int, per_sub: int,
             skip_set: set, include_list: list):

    with open(registry_path, "r") as f:
        registry = json.load(f)  # dict: {var_name: type_string}

    # Group by top-level prefix
    by_prefix = defaultdict(list)
    for name, plc_type in registry.items():
        prefix = name.split(".")[0]
        if plc_type.upper() in TYPE_MAP:
            by_prefix[prefix].append((name, plc_type.upper()))

    # Determine which subsystems to include
    if include_list:
        ordered = [p for p in include_list if p in by_prefix]
    else:
        # Sort by count descending, skip unwanted
        ordered = [p for p, _ in sorted(by_prefix.items(), key=lambda x: -len(x[1]))
                   if p not in skip_set]

    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)

    subsystem_files = []   # list of (subsystem_safe_name, var_count)
    global_idx = 0

    for prefix in ordered:
        if global_idx >= max_vars:
            break

        entries = by_prefix[prefix][:per_sub]
        # Further cap by remaining budget
        remaining = max_vars - global_idx
        entries = entries[:remaining]
        if not entries:
            continue

        safe = safe_name(prefix)
        lines = [SUBSYSTEM_HEADER.format(
            subsystem=safe, count=len(entries), start_idx=global_idx)]

        for entry_name, plc_type in entries:
            type_code, data_size = TYPE_MAP[plc_type]
            lines.append(ENTRY_TEMPLATE.format(
                idx=global_idx,
                name=entry_name,
                type_code=type_code,
                type_name=plc_type,
                data_size=data_size,
            ))
            global_idx += 1

        lines.append(SUBSYSTEM_FOOTER)

        fname = out / f"VarMon_RegInit_{safe}.st"
        fname.write_text("".join(lines), encoding="utf-8")
        subsystem_files.append((safe, len(entries)))
        print(f"  {fname.name}: {len(entries)} vars")

    # Dispatcher file
    dispatcher_lines = [DISPATCHER_HEADER.format(
        total=global_idx, num_subs=len(subsystem_files))]
    for safe, _ in subsystem_files:
        dispatcher_lines.append(f"    VarMon_RegInit_{safe};\n")
    dispatcher_lines.append(DISPATCHER_FOOTER.format(total=global_idx))

    dispatcher = out / "VarMon_RegInit.st"
    dispatcher.write_text("".join(dispatcher_lines), encoding="utf-8")

    print(f"\nDispatcher: {dispatcher}")
    print(f"Total: {global_idx} variables across {len(subsystem_files)} subsystems")
    print(f"\nAdd these files to IEC.prg:")
    for safe, _ in subsystem_files:
        print(f"  <File>VarMon_RegInit_{safe}.st</File>")

    # Also update IEC.prg automatically
    update_iec_prg(out, subsystem_files)


def update_iec_prg(outdir: Path, subsystem_files: list):
    """Add generated subsystem files to IEC.prg."""
    prg = outdir / "IEC.prg"
    if not prg.exists():
        return

    content = prg.read_text(encoding="utf-8")

    # Remove any previously generated subsystem lines
    import re
    content = re.sub(r'\s*<File>VarMon_RegInit_\w+\.st</File>\n?', '', content)

    # Build new lines
    new_lines = "".join(
        f'    <File Description="Registry: {safe} subsystem">VarMon_RegInit_{safe}.st</File>\n'
        for safe, _ in subsystem_files
    )

    # Insert before the closing </Files> tag
    content = content.replace("  </Files>", new_lines + "  </Files>")
    prg.write_text(content, encoding="utf-8")
    print(f"\nUpdated {prg}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate VarMon registry init files")
    parser.add_argument("--registry", default="plc_var_registry.json")
    parser.add_argument("--outdir", default="plc_code/VarMonitor",
                        help="Output directory (also updates IEC.prg there)")
    parser.add_argument("--max", type=int, default=80000, help="Max total variables")
    parser.add_argument("--per-sub", type=int, default=300, help="Max vars per subsystem file")
    parser.add_argument("--skip", default=",".join(DEFAULT_SKIP),
                        help="Comma-separated prefixes to skip")
    parser.add_argument("--include", default="",
                        help="Comma-separated prefixes to include (overrides --skip)")
    args = parser.parse_args()

    skip_set = set(args.skip.split(",")) if args.skip else set()
    include_list = [x for x in args.include.split(",") if x] if args.include else []

    generate(args.registry, args.outdir, args.max, args.per_sub, skip_set, include_list)

