"""
Generate VarMon registry init files from plc_var_registry.json.

Uses VarMonLib library: generates VM_RegVar() function calls instead of
direct struct assignments. Each subsystem is a separate ACTION file.
The dispatcher VarMon_RegInit.st calls each subsystem action in sequence.

Usage:
    python plc_var_codegen.py [options]

    --registry   path to plc_var_registry.json  (default: plc_var_registry.json)
    --outdir     output folder                  (default: plc_code/VarMonitor)
    --max        max total variables            (default: 2000)
    --per-sub    max variables per subsystem    (default: 300)
    --skip       comma-separated prefixes to skip (default: Hardware,MAIN)
    --include    comma-separated prefixes to include (default: all except skip list)

Example — include only Exit and WHS subsystems:
    python plc_var_codegen.py --include gExitCtrl,gWHS_Ctrl

Output files:
    VarMon_RegInit.st               — dispatcher (calls each subsystem action)
    VarMon_RegInit_<Subsystem>.st   — one file per subsystem, added to IEC.prg
"""

import json
import argparse
import re
from pathlib import Path
from collections import defaultdict

# Map PLC types to (type_code, data_size)
TYPE_MAP = {
    "BOOL":   (0, 1),
    "INT":    (1, 2),
    "UINT":   (2, 2),
    "DINT":   (3, 4),
    "UDINT":  (4, 4),
    "REAL":   (5, 4),
    "LREAL":  (6, 8),
    "STRING": (7, 0),
    "USINT":  (8, 1),
    "SINT":   (9, 1),
}

# Prefixes that are low-level hardware or internal — skip by default
DEFAULT_SKIP = {"MAIN"}

# Max variables per generated ACTION. Large subsystems are split into
# <CHUNK_SIZE-var sub-actions (VarMon_RegInit_<Sub>_p1, _p2, ...) so the
# stepped dispatcher can register one bounded chunk per PLC cycle without
# overrunning the task-class cycle time. See ProtoBufCom.st _CYCLIC driver.
#
# Sizing: each entry does VM_RegVarByName -> PV_xgetadr, a *name search through
# the PLC's PV catalog* costing ~10-50 us/entry (worse under high CPU load,
# e.g. firmware update at boot). At 1000/cycle this overran TC#7 (1.6 ms +
# 9.6 ms tolerance = 11.2 ms budget). 50/cycle keeps a build cycle under ~5 ms
# even at 100 us/entry; total build ~= 92k/50 * 1.6 ms ~= 3 s at startup.
CHUNK_SIZE = 50

# Per-subsystem file header (comment only; one or more ACTIONs follow).
FILE_HEADER = """\
(********************************************************************
 * VarMon Registry — {subsystem} subsystem
 * AUTO-GENERATED by codegen.py — DO NOT EDIT MANUALLY
 * Variables: {count}  |  Start index: {start_idx}  |  Chunks: {nchunks}
 ********************************************************************)
"""

ACTION_OPEN = "ACTION VarMon_RegInit_{name}:\n"

ENTRY_TEMPLATE = "    VM_RegVarByName(ADR(vmRegistry), {idx}, '{name}', {type_code}, {data_size});  (* {type_name} *)\n"

SUBSYSTEM_FOOTER = "END_ACTION\n"

# Stepped, re-entrant dispatcher: registers exactly ONE chunk per call.
DISPATCHER_HEADER = """\
(********************************************************************
 * VarMon Registry Init — STEPPED DISPATCHER (re-entrant)
 * AUTO-GENERATED by codegen.py — DO NOT EDIT MANUALLY
 * Registers ONE chunk per call; driven from ProtoBufCom _CYCLIC so the
 * ~{total} PV_xgetadr lookups are spread across cycles and never overrun
 * the TC#7 cycle time at startup.
 * Total steps: {steps}  |  vmRegCount: {regsize}
 ********************************************************************)
ACTION VarMon_RegInit_Step:
    CASE iRegStep OF
"""

DISPATCHER_STEP = "        {i}: VarMon_RegInit_{name};\n"

DISPATCHER_FOOTER = """\
    ELSE
        (* all chunks registered — finalize *)
        vmRegCount := {regsize};
        iRegDone := TRUE;
    END_CASE;

    IF NOT iRegDone THEN
        iRegStep := iRegStep + 1;
    END_IF;
END_ACTION
"""


def safe_name(prefix: str) -> str:
    """Make prefix safe as an ST action name suffix, preserving original case."""
    s = re.sub(r'[^A-Za-z0-9]', '_', prefix)
    return s[0].upper() + s[1:] if s else s


def _merge_case_collisions(by_prefix: dict) -> dict:
    """Merge prefixes that differ only by case (B&R / Windows are case-insensitive)."""
    # Group by lowercase safe_name
    groups = defaultdict(list)
    for prefix in by_prefix:
        key = safe_name(prefix).lower()
        groups[key].append(prefix)
    
    merged = defaultdict(list)
    for key, prefixes in groups.items():
        # Use the first prefix as canonical name
        canonical = prefixes[0]
        for p in prefixes:
            merged[canonical].extend(by_prefix[p])
    return merged


def generate(registry_path: str, outdir: str, max_vars: int,
             skip_set: set, include_list: list):

    with open(registry_path, "r") as f:
        registry = json.load(f)

    # Support two formats:
    # New: { "var_id": {"name": "...", "type": "..."}, ... }  (pre-assigned IDs)
    # Old: { "var_name": "type_string", ... }                 (sequential IDs)
    by_prefix = defaultdict(list)
    first_val = next(iter(registry.values()), None)
    if isinstance(first_val, dict):
        # New format — use pre-assigned var_id as index
        for idx_str, info in registry.items():
            idx = int(idx_str)
            name = info["name"]
            plc_type = info["type"].upper()
            prefix = name.split(".")[0]
            if plc_type in TYPE_MAP:
                by_prefix[prefix].append((idx, name, plc_type))
    else:
        # Old format — assign sequential IDs
        seq_idx = 0
        for name, plc_type_raw in registry.items():
            plc_type = plc_type_raw.upper()
            prefix = name.split(".")[0]
            if plc_type in TYPE_MAP:
                by_prefix[prefix].append((seq_idx, name, plc_type))
                seq_idx += 1

    # Determine which subsystems to include
    by_prefix = _merge_case_collisions(by_prefix)
    if include_list:
        ordered = [p for p in include_list if p in by_prefix]
    else:
        # Sort by count descending, skip unwanted
        ordered = [p for p, _ in sorted(by_prefix.items(), key=lambda x: -len(x[1]))
                   if p not in skip_set]

    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)

    # Clean up old generated files to avoid stale duplicates
    for old_file in out.glob("VarMon_RegInit_*.st"):
        old_file.unlink()

    subsystem_files = []   # list of (subsystem_safe_name, var_count)
    step_actions = []      # ordered action names for the stepped dispatcher
    global_idx = 0
    max_var_id = 0

    for prefix in ordered:
        if global_idx >= max_vars:
            break

        entries = by_prefix[prefix]
        # Cap by remaining budget
        remaining = max_vars - global_idx
        entries = entries[:remaining]
        if not entries:
            continue

        safe = safe_name(prefix)
        start_idx = entries[0][0]

        # Split the subsystem into <=CHUNK_SIZE-var chunks. One chunk = one
        # ACTION = one dispatcher step = bounded per-cycle work.
        chunks = [entries[i:i + CHUNK_SIZE]
                  for i in range(0, len(entries), CHUNK_SIZE)]

        lines = [FILE_HEADER.format(
            subsystem=safe, count=len(entries),
            start_idx=start_idx, nchunks=len(chunks))]

        for k, chunk in enumerate(chunks, 1):
            # Single-chunk subsystems keep the bare name; split ones get _pK.
            name = safe if len(chunks) == 1 else f"{safe}_p{k}"
            lines.append(ACTION_OPEN.format(name=name))
            for var_idx, entry_name, plc_type in chunk:
                type_code, data_size = TYPE_MAP[plc_type]
                lines.append(ENTRY_TEMPLATE.format(
                    idx=var_idx,
                    name=entry_name,
                    type_code=type_code,
                    type_name=plc_type,
                    data_size=data_size,
                ))
                global_idx += 1
                if var_idx > max_var_id:
                    max_var_id = var_idx
            lines.append(SUBSYSTEM_FOOTER)
            if k != len(chunks):
                lines.append("\n")
            step_actions.append(name)

        fname = out / f"VarMon_RegInit_{safe}.st"
        fname.write_text("".join(lines), encoding="utf-8")
        subsystem_files.append((safe, len(entries)))
        print(f"  {fname.name}: {len(entries)} vars in {len(chunks)} chunk(s)")

    # Dispatcher file (stepped state machine)
    registry_size = max_var_id + 1
    dispatcher_lines = [DISPATCHER_HEADER.format(
        total=global_idx, steps=len(step_actions), regsize=registry_size)]
    for i, name in enumerate(step_actions):
        dispatcher_lines.append(DISPATCHER_STEP.format(i=i, name=name))
    dispatcher_lines.append(DISPATCHER_FOOTER.format(regsize=registry_size))

    dispatcher = out / "VarMon_RegInit.st"
    dispatcher.write_text("".join(dispatcher_lines), encoding="utf-8")

    print(f"\nDispatcher: {dispatcher}")
    print(f"Total: {global_idx} variables across {len(subsystem_files)} "
          f"subsystems, {len(step_actions)} chunk steps")
    print(f"\nAdd these files to IEC.prg:")
    for safe, _ in subsystem_files:
        print(f"  <File>VarMon_RegInit_{safe}.st</File>")

    # Also update IEC.prg automatically
    update_iec_prg(out, subsystem_files)

    # Auto-update ProtoBufCom.var array size
    update_var_file(out, max_var_id)


def update_var_file(outdir: Path, max_var_id: int):
    """Update vmRegistry array size in ProtoBufCom.var."""
    var_file = outdir / "ProtoBufCom.var"
    if not var_file.exists():
        return
    import re
    content = var_file.read_text(encoding="utf-8")
    new_content = re.sub(
        r'vmRegistry\s*:\s*ARRAY\[0\.\.\d+\]\s*OF\s*VM_VarEntry_typ',
        f'vmRegistry : ARRAY[0..{max_var_id}] OF VM_VarEntry_typ',
        content
    )

    # Ensure the chunked-build driver state vars exist (referenced by the
    # stepped dispatcher + ProtoBufCom.st _CYCLIC). Inject before END_VAR
    # if a fresh branch's .var doesn't declare them yet.
    if "iRegStep" not in new_content:
        inject = ("    (* Chunked registry build state (see ProtoBufCom.st) *)\n"
                  "    iRegStep   : UDINT;\n"
                  "    iRegDone   : BOOL;\n")
        new_content = re.sub(r'(\n[ \t]*END_VAR)', "\n" + inject + r'\1',
                             new_content, count=1)

    if new_content != content:
        var_file.write_text(new_content, encoding="utf-8")
        print(f"Updated {var_file} -> ARRAY[0..{max_var_id}] (+ driver vars)")


def update_iec_prg(outdir: Path, subsystem_files: list):
    """Add generated subsystem files to IEC.prg."""
    prg = outdir / "IEC.prg"
    if not prg.exists():
        return

    content = prg.read_text(encoding="utf-8")

    # Remove any previously generated subsystem lines (with or without Description attr)
    import re
    content = re.sub(r'\s*<File[^>]*>VarMon_RegInit_\w+\.st</File>\n?', '', content)

    # Build new lines
    new_lines = "".join(
        f'    <File Description="Registry: {safe} subsystem">VarMon_RegInit_{safe}.st</File>\n'
        for safe, _ in subsystem_files
    )

    # Insert before the closing </Files> tag
    content = content.replace("  </Files>", new_lines + "  </Files>")
    prg.write_text(content, encoding="utf-8")
    print(f"\nUpdated {prg}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate VarMon registry init files")
    parser.add_argument("--registry", default="plc_var_registry.json")
    parser.add_argument("--outdir", default="plc_code/VarMonitor",
                        help="Output directory for generated .st files (also updates IEC.prg)")
    parser.add_argument("--max", type=int, default=100000, help="Max total variables")
    parser.add_argument("--chunk", type=int, default=CHUNK_SIZE,
                        help="Max variables per generated ACTION / dispatcher step")
    parser.add_argument("--skip", default=",".join(DEFAULT_SKIP),
                        help="Comma-separated prefixes to skip")
    parser.add_argument("--include", default="",
                        help="Comma-separated prefixes to include (overrides --skip)")
    args = parser.parse_args()

    skip_set = set(args.skip.split(",")) if args.skip else set()
    include_list = [x for x in args.include.split(",") if x] if args.include else []

    CHUNK_SIZE = args.chunk

    generate(args.registry, args.outdir, args.max, skip_set, include_list)

