# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plcmonitor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plcmonitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10plcmonitor.proto\x12\nplcmonitor\"\xb1\x01\n\x08VarValue\x12\x0e\n\x06var_id\x18\x01 \x01(\r\x12\x12\n\x08\x62ool_val\x18\x02 \x01(\x08H\x00\x12\x11\n\x07int_val\x18\x03 \x01(\x05H\x00\x12\x12\n\x08uint_val\x18\x04 \x01(\rH\x00\x12\x12\n\x08\x64int_val\x18\x05 \x01(\x03H\x00\x12\x12\n\x08real_val\x18\x06 \x01(\x02H\x00\x12\x13\n\tlreal_val\x18\x07 \x01(\x01H\x00\x12\x14\n\nstring_val\x18\x08 \x01(\tH\x00\x42\x07\n\x05value\"\\\n\x0fVarUpdatePacket\x12\x10\n\x08sequence\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12$\n\x06values\x18\x03 \x03(\x0b\x32\x14.plcmonitor.VarValue\"\x95\x01\n\x10SubscribeCommand\x12\x33\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32#.plcmonitor.SubscribeCommand.Action\x12\x0f\n\x07var_ids\x18\x02 \x03(\r\x12\x13\n\x0binterval_ms\x18\x03 \x01(\r\"&\n\x06\x41\x63tion\x12\x07\n\x03SET\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06REMOVE\x10\x02\"(\n\x0fRegistryRequest\x12\x15\n\rfull_registry\x18\x01 \x01(\x08\"B\n\x10VarRegistryEntry\x12\x0e\n\x06var_id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08plc_type\x18\x03 \x01(\t\"D\n\x13VarRegistryResponse\x12-\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1c.plcmonitor.VarRegistryEntry\"\xf6\x02\n\nPlcMessage\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.plcmonitor.PlcMessage.MsgType\x12-\n\x06update\x18\x02 \x01(\x0b\x32\x1b.plcmonitor.VarUpdatePacketH\x00\x12\x31\n\tsubscribe\x18\x03 \x01(\x0b\x32\x1c.plcmonitor.SubscribeCommandH\x00\x12.\n\x07reg_req\x18\x04 \x01(\x0b\x32\x1b.plcmonitor.RegistryRequestH\x00\x12\x33\n\x08reg_resp\x18\x05 \x01(\x0b\x32\x1f.plcmonitor.VarRegistryResponseH\x00\"h\n\x07MsgType\x12\x0e\n\nVAR_UPDATE\x10\x00\x12\x11\n\rSUBSCRIBE_CMD\x10\x01\x12\x14\n\x10REGISTRY_REQUEST\x10\x02\x12\x15\n\x11REGISTRY_RESPONSE\x10\x03\x12\r\n\tHEARTBEAT\x10\x04\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plcmonitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VARVALUE']._serialized_start=33
  _globals['_VARVALUE']._serialized_end=210
  _globals['_VARUPDATEPACKET']._serialized_start=212
  _globals['_VARUPDATEPACKET']._serialized_end=304
  _globals['_SUBSCRIBECOMMAND']._serialized_start=307
  _globals['_SUBSCRIBECOMMAND']._serialized_end=456
  _globals['_SUBSCRIBECOMMAND_ACTION']._serialized_start=418
  _globals['_SUBSCRIBECOMMAND_ACTION']._serialized_end=456
  _globals['_REGISTRYREQUEST']._serialized_start=458
  _globals['_REGISTRYREQUEST']._serialized_end=498
  _globals['_VARREGISTRYENTRY']._serialized_start=500
  _globals['_VARREGISTRYENTRY']._serialized_end=566
  _globals['_VARREGISTRYRESPONSE']._serialized_start=568
  _globals['_VARREGISTRYRESPONSE']._serialized_end=636
  _globals['_PLCMESSAGE']._serialized_start=639
  _globals['_PLCMESSAGE']._serialized_end=1013
  _globals['_PLCMESSAGE_MSGTYPE']._serialized_start=898
  _globals['_PLCMESSAGE_MSGTYPE']._serialized_end=1002
# @@protoc_insertion_point(module_scope)
