"""
PLC Variable Monitor — Gateway Engine
Handles TCP connection to PLC for subscription commands and
UDP reception for variable value updates.

Wire protocol (PLC → Python, UDP):
  [MAGIC:2B=0xAB01][SEQ:4B][TIMESTAMP:4B][COUNT:2B]
  Per var: [VAR_ID:4B][TYPE:1B][VALUE: variable]

Wire protocol (Python → PLC, TCP):
  [CMD:1B][COUNT:2B LE][PAYLOAD: COUNT x 4B LE]
"""

import json
import math
import socket
import struct
import threading
import time
from collections import deque
from pathlib import Path
from typing import Callable

# Type codes matching PLC VM_TypeCode_enum
TYPE_BOOL   = 0
TYPE_INT    = 1
TYPE_UINT   = 2
TYPE_DINT   = 3
TYPE_UDINT  = 4
TYPE_REAL   = 5
TYPE_LREAL  = 6
TYPE_STRING = 7
TYPE_USINT  = 8
TYPE_SINT   = 9

MAGIC = 0xAB01
TCP_PORT = 55000
UDP_PORT = 55001


class PlcMonitorEngine:
    """Manages PLC connection, subscriptions, and variable data."""

    def __init__(self):
        self.plc_ip: str = ""
        self.connected = False
        self._tcp_sock: socket.socket | None = None
        self._udp_sock: socket.socket | None = None
        self._rx_thread: threading.Thread | None = None
        self._udp_thread: threading.Thread | None = None
        self._running = False
        self._lock = threading.Lock()

        # Variable registry: var_id → {name, plc_type}
        self.registry: dict[int, dict] = {}
        # Reverse map: name → var_id
        self.name_to_id: dict[str, int] = {}
        # Available vars (discovered on PLC): set of var_id that actually exist
        self.available_vars: set[int] = set()
        self._discovery_done = False
        self._discovering = False
        # Current values cache: var_id → value
        self.values: dict[int, any] = {}
        # Per-variable change timestamps: var_id → {plc_ts, py_ts}
        # plc_ts = PLC timestamp in ms (from packet header)
        # py_ts  = Python wall-clock time (time.time()) when change detected
        self.last_changed: dict[int, dict] = {}
        # Active subscription set: set of var_id
        self.subscribed: set[int] = set()
        # Callback for value updates
        self._on_update: Callable | None = None
        # Stats
        self.stats = {
            "packets_received": 0,
            "last_seq": 0,
            "last_timestamp": 0,
            "dropped_packets": 0,
            "bytes_received": 0,
        }
        # Detailed performance stats
        self._stats_lock = threading.Lock()
        self._stats_start_time: float = 0.0
        self._last_packet_py_time: float = 0.0
        self._inter_packet_times: deque[float] = deque(maxlen=10000)
        self._plc_timestamps: deque[int] = deque(maxlen=10000)
        self._per_var_changes: dict[int, int] = {}  # var_id → change count
        self._per_var_prev: dict[int, any] = {}      # var_id → previous value
        self._total_var_updates: int = 0
        self._seq_gaps: list[tuple] = []   # (prev_seq, cur_seq, ts_gap, missed)
        self._seq_step_counts: dict[int, int] = {}  # seq_step → count
        # Benchmark state
        self._bench_running = False
        self._bench_start: float = 0.0
        self._bench_duration: float = 0.0
        self._bench_packets: int = 0
        self._bench_var_updates: int = 0
        self._bench_var_changes: int = 0
        self._bench_drops: int = 0
        self._bench_inter_pkt: list[float] = []
        self._bench_plc_ts: list[int] = []
        self._bench_per_var_changes: dict[int, int] = {}
        self._bench_done = False
        self._bench_result: dict | None = None

    def load_registry(self, registry_path: str | Path | None = None):
        """Load variable registry from JSON file (generated by plc_registry_from_st.py).
        Format: { "plc_index": {"name": "...", "type": "..."}, ... }"""
        if registry_path is None:
            registry_path = Path(__file__).parent.parent / "plc_var_registry.json"

        with open(registry_path) as f:
            raw = json.load(f)

        self.registry.clear()
        self.name_to_id.clear()

        for idx_str, info in raw.items():
            idx = int(idx_str)
            if isinstance(info, dict):
                # New format: {"name": "...", "type": "..."}
                self.registry[idx] = {"name": info["name"], "plc_type": info["type"]}
                self.name_to_id[info["name"]] = idx
            else:
                # Legacy format: name → type (sequential index)
                self.registry[idx] = {"name": idx_str, "plc_type": info}
                self.name_to_id[idx_str] = idx

    def _iter_visible_vars(self):
        """Iterate over variables visible to the UI.
        If discovery has been done, only yield available vars.
        Otherwise yield all registry vars (pre-discovery fallback)."""
        if self._discovery_done and self.available_vars:
            for var_id in self.available_vars:
                info = self.registry.get(var_id)
                if info:
                    yield var_id, info
        else:
            yield from self.registry.items()

    def get_default_vars(self, prefix: str = "gProtoTest") -> list[dict]:
        """Return all leaf variables under a prefix (for auto-selection)."""
        result = []
        for var_id, info in self._iter_visible_vars():
            if info["name"].startswith(prefix + ".") or info["name"] == prefix:
                result.append({
                    "id": str(var_id),
                    "name": info["name"],
                    "plc_type": info["plc_type"],
                })
        return result

    def get_tree(self) -> list[dict]:
        """Build a tree structure from flat variable paths for UI browsing."""
        tree = {}
        for var_id, info in self.registry.items():
            parts = info["name"].split(".")
            node = tree
            for i, part in enumerate(parts):
                if part not in node:
                    node[part] = {"_children": {}, "_vars": []}
                if i == len(parts) - 1:
                    node[part]["_vars"].append({
                        "id": var_id,
                        "name": info["name"],
                        "leaf": parts[-1],
                        "plc_type": info["plc_type"],
                    })
                else:
                    node = node[part]["_children"]
        return self._tree_to_list(tree, "")

    def _tree_to_list(self, node: dict, prefix: str) -> list[dict]:
        """Convert nested dict tree to flat list for API."""
        result = []
        for key, val in sorted(node.items()):
            if key.startswith("_"):
                continue
            path = f"{prefix}.{key}" if prefix else key
            children = val.get("_children", {})
            vars_here = val.get("_vars", [])

            if vars_here:
                for v in vars_here:
                    result.append({
                        "id": str(v["id"]),
                        "name": v["leaf"],
                        "full_name": v["name"],
                        "is_variable": True,
                        "has_children": False,
                        "plc_type": v["plc_type"],
                        "value": str(self.values.get(v["id"], "—")),
                    })
            if children:
                result.append({
                    "id": f"folder:{path}",
                    "name": key,
                    "full_name": path,
                    "is_variable": False,
                    "has_children": True,
                })
        return result

    def browse(self, node_id: str | None = None) -> list[dict]:
        """Browse children of a node (for lazy tree loading)."""
        if not self.registry:
            return []

        if node_id is None:
            # Root level — return top-level struct variable names
            roots = {}
            for var_id, info in self._iter_visible_vars():
                top = info["name"].split(".")[0]
                if top not in roots:
                    roots[top] = {"count": 0}
                roots[top]["count"] += 1

            return [
                {
                    "id": f"node:{name}",
                    "name": name,
                    "is_variable": False,
                    "has_children": True,
                    "value": f"({info['count']} fields)",
                }
                for name, info in sorted(roots.items())
            ]

        # Find children of this node
        if node_id.startswith("node:"):
            prefix = node_id[5:]
        elif node_id.startswith("folder:"):
            prefix = node_id[7:]
        else:
            return []

        # Find all vars/folders under this prefix
        children = {}
        for var_id, info in self._iter_visible_vars():
            name = info["name"]
            if not name.startswith(prefix + "."):
                continue
            rest = name[len(prefix) + 1:]
            parts = rest.split(".")
            next_part = parts[0]

            if len(parts) == 1:
                # Leaf variable
                children[f"var:{var_id}"] = {
                    "id": str(var_id),
                    "name": next_part,
                    "full_name": name,
                    "is_variable": True,
                    "has_children": False,
                    "plc_type": info["plc_type"],
                    "value": str(self.values.get(var_id, "—")),
                }
            else:
                # Subfolder
                folder_path = f"{prefix}.{next_part}"
                if folder_path not in children:
                    children[folder_path] = {
                        "id": f"node:{folder_path}",
                        "name": next_part,
                        "is_variable": False,
                        "has_children": True,
                    }

        return list(children.values())

    # ── Connection ───────────────────────────────────────────────
    def connect(self, plc_ip: str) -> dict:
        """Connect to PLC via TCP (commands + data stream)."""
        with self._lock:
            # Always tear down any existing connection first
            if self.connected or self._tcp_sock is not None:
                self.disconnect()

            self.plc_ip = plc_ip

            # TCP connection for subscription commands and data stream
            try:
                self._tcp_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                self._tcp_sock.settimeout(3.0)
                self._tcp_sock.connect((plc_ip, TCP_PORT))
                self._tcp_sock.settimeout(1.0)
            except Exception as e:
                self._tcp_sock = None
                return {"ok": False, "error": f"TCP connect failed: {e}"}

            self.connected = True
            self._running = True

            # Start TCP receiver thread (for ACKs/responses from PLC)
            self._rx_thread = threading.Thread(
                target=self._tcp_receive_loop, daemon=True
            )
            self._rx_thread.start()

            # Open UDP socket for receiving variable data from PLC
            try:
                self._udp_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                self._udp_sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                self._udp_sock.bind(("0.0.0.0", UDP_PORT))
                self._udp_sock.settimeout(1.0)
            except Exception as e:
                print(f"[UDP] Failed to bind port {UDP_PORT}: {e}")
                # Non-fatal — TCP data path may still work
                self._udp_sock = None

            if self._udp_sock:
                self._udp_thread = threading.Thread(
                    target=self._udp_receive_loop, daemon=True
                )
                self._udp_thread.start()

            return {"ok": True, "url": f"{plc_ip}:{TCP_PORT}"}

    def discover_available(self, batch_size: int = 500,
                           batch_wait_s: float = 0.15) -> dict:
        """Discover which variables actually exist on the connected PLC.
        Subscribes in small batches (PLC subscription array is 500 max)
        and collects which var_ids produce data — those have pAddress
        resolved on the PLC."""
        if not self.connected:
            return {"ok": False, "error": "Not connected"}
        if self._discovering:
            return {"ok": False, "error": "Discovery already in progress"}

        self._discovering = True
        self.available_vars.clear()
        self._discovery_done = False

        all_ids = sorted(self.registry.keys())
        if not all_ids:
            self._discovering = False
            return {"ok": False, "error": "Registry is empty"}

        # Set a fast interval for discovery
        self._send_tcp_command(0x04, [], count_override=10)
        time.sleep(0.05)

        # Process in batches — subscribe each batch with SET, wait, collect
        total_batches = (len(all_ids) + batch_size - 1) // batch_size
        for batch_num, i in enumerate(range(0, len(all_ids), batch_size)):
            if not self._running:
                break
            batch = all_ids[i:i + batch_size]
            # SET this batch (replaces previous subscription)
            self._send_tcp_command(0x01, batch)
            # Wait for PLC to respond with data for valid vars in this batch
            time.sleep(batch_wait_s)
            # Collect any var_ids that appeared in values during this window
            self.available_vars.update(self.values.keys())
            # Clear values for next batch
            self.values.clear()
            if (batch_num + 1) % 10 == 0:
                print(f"[DISCOVERY] Batch {batch_num+1}/{total_batches} "
                      f"— found {len(self.available_vars)} so far")

        # Clear subscription
        self._send_tcp_command(0x01, [])
        self.subscribed.clear()
        self.values.clear()
        self.last_changed.clear()

        self._discovery_done = True
        self._discovering = False

        print(f"[DISCOVERY] Found {len(self.available_vars)} available variables "
              f"out of {len(self.registry)} in registry")

        return {
            "ok": True,
            "available_count": len(self.available_vars),
            "registry_count": len(self.registry),
        }

    def get_discovery_status(self) -> dict:
        """Return current discovery state."""
        return {
            "done": self._discovery_done,
            "discovering": self._discovering,
            "available_count": len(self.available_vars),
            "registry_count": len(self.registry),
        }

    def disconnect(self) -> dict:
        """Disconnect from PLC."""
        with self._lock:
            self._running = False
            if self._tcp_sock:
                try:
                    self._tcp_sock.close()
                except Exception:
                    pass
                self._tcp_sock = None
            if self._udp_sock:
                try:
                    self._udp_sock.close()
                except Exception:
                    pass
                self._udp_sock = None
            self.connected = False
            self.subscribed.clear()
        return {"ok": True}

    # ── Subscription commands ────────────────────────────────────
    def subscribe(self, var_names: list[str]) -> dict:
        """Subscribe to variables by name. Sends SET command to PLC."""
        var_ids = []
        not_found = []
        for name in var_names:
            if name in self.name_to_id:
                var_ids.append(self.name_to_id[name])
            else:
                not_found.append(name)

        if not var_ids:
            return {"ok": False, "error": "No valid variable names", "not_found": not_found}

        self.subscribed = set(var_ids)
        self._send_tcp_command(0x01, var_ids)

        return {
            "ok": True,
            "subscribed": len(var_ids),
            "not_found": not_found,
        }

    def subscribe_by_ids(self, var_ids: list[int]) -> dict:
        """Subscribe by numeric var_ids."""
        valid = [vid for vid in var_ids if vid in self.registry]
        self.subscribed = set(valid)
        self._send_tcp_command(0x01, valid)
        return {"ok": True, "subscribed": len(valid)}

    def set_interval(self, interval_ms: int) -> dict:
        """Set PLC send interval."""
        interval_ms = max(1, min(10000, interval_ms))
        self._send_tcp_command(0x04, [], count_override=interval_ms)
        return {"ok": True, "interval_ms": interval_ms}

    def _send_tcp_command(self, cmd: int, var_ids: list[int],
                          count_override: int | None = None):
        """Send a TCP command to PLC."""
        if not self._tcp_sock:
            return

        count = count_override if count_override is not None else len(var_ids)
        buf = struct.pack("<BH", cmd, count)
        for vid in var_ids:
            buf += struct.pack("<I", vid)  # UDINT — 4 bytes

        try:
            self._tcp_sock.sendall(buf)
            print(f"[TCP TX] cmd=0x{cmd:02X} count={count} payload={len(buf)}B")
        except Exception as e:
            print(f"[TCP TX ERROR] cmd=0x{cmd:02X}: {e}")
            self.connected = False
            try:
                self._tcp_sock.close()
            except Exception:
                pass
            self._tcp_sock = None

    # ── TCP Receiver ─────────────────────────────────────────────
    def _tcp_receive_loop(self):
        """Background thread: receive data packets from PLC over TCP."""
        print(f"[TCP RX] Receiver started")
        buf = b""
        while self._running:
            try:
                chunk = self._tcp_sock.recv(4096)
                if not chunk:
                    print("[TCP RX] Connection closed by PLC")
                    self.connected = False
                    break
                buf += chunk
                # Process all complete packets in the buffer
                buf = self._process_tcp_buffer(buf)
            except socket.timeout:
                continue
            except OSError:
                break
        print("[TCP RX] Thread stopped")

    # ── UDP Receiver ─────────────────────────────────────────────
    def _udp_receive_loop(self):
        """Background thread: receive variable data packets from PLC via UDP."""
        print(f"[UDP RX] Receiver started on port {UDP_PORT}")
        while self._running:
            try:
                data, addr = self._udp_sock.recvfrom(1500)
                if data and len(data) >= 12:
                    self._decode_packet(data)
            except socket.timeout:
                continue
            except OSError:
                break
        print("[UDP RX] Thread stopped")

    def _process_tcp_buffer(self, buf: bytes) -> bytes:
        """Extract and decode complete packets from TCP stream buffer.
        Returns the remaining unprocessed bytes."""
        while len(buf) >= 12:  # Minimum header size
            # Look for magic bytes 0xAB01
            magic = struct.unpack_from("<H", buf, 0)[0]
            if magic != MAGIC:
                # Not a data packet — could be a 3-byte ACK from PLC
                # Skip 1 byte and rescan
                buf = buf[1:]
                continue

            # We have a valid header — try to determine full packet size
            _, seq, timestamp, count = struct.unpack_from("<HIIH", buf, 0)

            # We need to scan through to find packet length
            # (variable-length fields make this necessary)
            pkt_len = self._calc_packet_len(buf, count)
            if pkt_len is None or pkt_len > len(buf):
                break  # Incomplete packet, wait for more data

            # Extract and decode complete packet
            pkt = buf[:pkt_len]
            buf = buf[pkt_len:]
            self._decode_packet(pkt)

        return buf

    def _calc_packet_len(self, data: bytes, count: int) -> int | None:
        """Calculate total packet length by walking the variable entries."""
        offset = 12  # After header
        for _ in range(count):
            if offset + 5 > len(data):
                return None  # Incomplete
            type_code = data[offset + 4]  # type byte after 4-byte var_id
            offset += 5
            if type_code in (TYPE_BOOL, TYPE_USINT, TYPE_SINT):
                offset += 1
            elif type_code in (TYPE_INT, TYPE_UINT):
                offset += 2
            elif type_code in (TYPE_DINT, TYPE_UDINT, TYPE_REAL):
                offset += 4
            elif type_code == TYPE_LREAL:
                offset += 8
            elif type_code == TYPE_STRING:
                if offset >= len(data):
                    return None
                str_len = data[offset]
                offset += 1 + str_len
            else:
                return None  # Unknown type
            if offset > len(data):
                return None
        return offset

    def _decode_packet(self, data: bytes):
        """Decode a variable update packet."""
        if len(data) < 12:
            return

        magic, seq, timestamp, count = struct.unpack_from("<HIIH", data, 0)
        if magic != MAGIC:
            return

        py_now = time.perf_counter()

        with self._stats_lock:
            # Stats
            if self.stats["packets_received"] == 0:
                self._stats_start_time = py_now

            # Detect drops using PLC timestamp gaps:
            # If the gap between consecutive PLC timestamps is much larger
            # than the typical interval, packets were lost.
            # Track sequence step to learn the PLC's actual increment pattern.
            prev_seq = self.stats["last_seq"]
            prev_ts = self.stats["last_timestamp"]
            if prev_seq > 0:
                seq_step = seq - prev_seq
                # Track the most common seq step (PLC may skip seq numbers)
                self._seq_step_counts[seq_step] = self._seq_step_counts.get(seq_step, 0) + 1
                # Use PLC timestamp gap to detect real drops:
                # If ts gap > 2x the median PLC interval, count missed packets
                if prev_ts > 0 and len(self._plc_timestamps) > 10:
                    ts_gap = timestamp - prev_ts
                    # Expect ~20ms per packet; if gap > 50ms, we missed some
                    expected_interval = self._get_median_plc_interval()
                    if expected_interval > 0 and ts_gap > expected_interval * 2.5:
                        missed = round(ts_gap / expected_interval) - 1
                        self.stats["dropped_packets"] += missed
                        self._seq_gaps.append((prev_seq, seq, ts_gap, missed))

            self.stats["last_seq"] = seq
            self.stats["seq_step_mode"] = max(self._seq_step_counts, key=self._seq_step_counts.get) if self._seq_step_counts else 1
            self.stats["last_timestamp"] = timestamp
            self.stats["packets_received"] += 1
            self.stats["bytes_received"] += len(data)

            # Inter-packet timing
            if self._last_packet_py_time > 0:
                dt_ms = (py_now - self._last_packet_py_time) * 1000
                self._inter_packet_times.append(dt_ms)
            self._last_packet_py_time = py_now

            # PLC timestamps
            self._plc_timestamps.append(timestamp)

        # Decode variable values
        offset = 12  # After header
        updates = {}
        raw_updates = {}  # var_id → value (for stats tracking)

        for i in range(count):
            if offset + 3 > len(data):
                break

            var_id, type_code = struct.unpack_from("<IB", data, offset)  # UDINT var_id
            offset += 5

            value = None
            try:
                if type_code == TYPE_BOOL:
                    value = bool(data[offset])
                    offset += 1
                elif type_code == TYPE_INT:
                    value = struct.unpack_from("<h", data, offset)[0]
                    offset += 2
                elif type_code == TYPE_UINT:
                    value = struct.unpack_from("<H", data, offset)[0]
                    offset += 2
                elif type_code == TYPE_DINT:
                    value = struct.unpack_from("<i", data, offset)[0]
                    offset += 4
                elif type_code == TYPE_UDINT:
                    value = struct.unpack_from("<I", data, offset)[0]
                    offset += 4
                elif type_code == TYPE_REAL:
                    value = round(struct.unpack_from("<f", data, offset)[0], 6)
                    offset += 4
                elif type_code == TYPE_LREAL:
                    value = round(struct.unpack_from("<d", data, offset)[0], 9)
                    offset += 8
                elif type_code == TYPE_STRING:
                    str_len = data[offset]
                    offset += 1
                    value = data[offset:offset + str_len].decode("ascii", errors="replace")
                    offset += str_len
                elif type_code == TYPE_USINT:
                    value = data[offset]
                    offset += 1
                elif type_code == TYPE_SINT:
                    value = struct.unpack_from("<b", data, offset)[0]
                    offset += 1
            except (struct.error, IndexError):
                break

            if value is not None:
                self.values[var_id] = value
                raw_updates[var_id] = value
                info = self.registry.get(var_id)
                if info:
                    updates[info["name"]] = value

        # Track per-variable changes and record change timestamps
        wall_time = time.time()
        with self._stats_lock:
            self._total_var_updates += len(raw_updates)
            for vid, val in raw_updates.items():
                prev = self._per_var_prev.get(vid)
                if prev is not None and prev != val:
                    self._per_var_changes[vid] = self._per_var_changes.get(vid, 0) + 1
                    self.last_changed[vid] = {"plc_ts": timestamp, "py_ts": wall_time}
                elif prev is None:
                    # First time seeing this variable — record initial timestamp
                    self.last_changed[vid] = {"plc_ts": timestamp, "py_ts": wall_time}
                self._per_var_prev[vid] = val

        # Benchmark recording
        if self._bench_running:
            self._record_benchmark(seq, timestamp, raw_updates, py_now, len(data))

        # Notify callback
        if updates and self._on_update:
            self._on_update(timestamp, updates)

    def set_on_update(self, callback: Callable[[int, dict], None]):
        """Set callback for value updates: callback(timestamp_ms, {name: value})."""
        self._on_update = callback

    # ── Read current values ──────────────────────────────────────
    def read_values(self, names: list[str]) -> dict:
        """Read current cached values for given variable names.
        Returns {name: {value, last_changed_plc_ts, last_changed_py_ts}}."""
        result = {}
        for name in names:
            var_id = self.name_to_id.get(name)
            if var_id is not None:
                entry = {"value": self.values.get(var_id, None)}
                changed = self.last_changed.get(var_id)
                if changed:
                    entry["last_changed_plc_ts"] = changed["plc_ts"]
                    entry["last_changed_py_ts"] = changed["py_ts"]
                result[name] = entry
        return result

    def get_all_values(self) -> dict:
        """Get all currently cached values with change timestamps."""
        result = {}
        for var_id, value in self.values.items():
            info = self.registry.get(var_id)
            if info:
                entry = {"value": value}
                changed = self.last_changed.get(var_id)
                if changed:
                    entry["last_changed_plc_ts"] = changed["plc_ts"]
                    entry["last_changed_py_ts"] = changed["py_ts"]
                result[info["name"]] = entry
        return result

    # ── Search ───────────────────────────────────────────────────
    def search(self, query: str, limit: int = 100) -> list[dict]:
        """Search variable names by substring (only available vars after discovery)."""
        query_lower = query.lower()
        results = []
        for var_id, info in self._iter_visible_vars():
            if query_lower in info["name"].lower():
                results.append({
                    "id": str(var_id),
                    "name": info["name"],
                    "plc_type": info["plc_type"],
                    "value": str(self.values.get(var_id, "—")),
                    "is_variable": True,
                    "has_children": False,
                })
                if len(results) >= limit:
                    break
        return results

    # ── Stats / Benchmark ────────────────────────────────────────
    def reset_stats(self):
        """Reset all live statistics."""
        with self._stats_lock:
            self.stats = {
                "packets_received": 0, "last_seq": 0, "last_timestamp": 0,
                "dropped_packets": 0, "bytes_received": 0,
            }
            self._stats_start_time = time.perf_counter()
            self._last_packet_py_time = 0.0
            self._inter_packet_times.clear()
            self._plc_timestamps.clear()
            self._per_var_changes.clear()
            self._per_var_prev.clear()
            self._total_var_updates = 0
            self._seq_gaps.clear()
            self._seq_step_counts.clear()

    def get_detailed_stats(self) -> dict:
        """Return comprehensive statistics snapshot."""
        with self._stats_lock:
            elapsed = time.perf_counter() - self._stats_start_time if self._stats_start_time else 0
            pkts = self.stats["packets_received"]
            pkt_rate = pkts / elapsed if elapsed > 0 else 0
            var_rate = self._total_var_updates / elapsed if elapsed > 0 else 0

            # Inter-packet timing
            ipt = list(self._inter_packet_times)
            ipt_stats = self._calc_timing_stats(ipt) if ipt else {}

            # PLC timestamp jitter (inter-timestamp deltas)
            plc_ts = list(self._plc_timestamps)
            plc_deltas = []
            for i in range(1, len(plc_ts)):
                d = plc_ts[i] - plc_ts[i - 1]
                if 0 < d < 10000:  # Filter wraps/outliers
                    plc_deltas.append(d)
            plc_stats = self._calc_timing_stats(plc_deltas) if plc_deltas else {}

            # Per-variable change rates (top 30 by change count)
            per_var = []
            for vid, cnt in sorted(self._per_var_changes.items(), key=lambda x: -x[1])[:30]:
                info = self.registry.get(vid)
                per_var.append({
                    "name": info["name"] if info else f"var_{vid}",
                    "plc_type": info["plc_type"] if info else "?",
                    "changes": cnt,
                    "rate": cnt / elapsed if elapsed > 0 else 0,
                })

            total_changes = sum(self._per_var_changes.values())
            n_subs = len(self.subscribed)

            return {
                "elapsed_s": round(elapsed, 1),
                "packets_received": pkts,
                "packet_rate": round(pkt_rate, 1),
                "total_var_updates": self._total_var_updates,
                "var_update_rate": round(var_rate, 1),
                "total_var_changes": total_changes,
                "var_change_rate": round(total_changes / elapsed, 1) if elapsed > 0 else 0,
                "dropped_packets": self.stats["dropped_packets"],
                "drop_pct": round(100 * self.stats["dropped_packets"] / max(1, pkts + self.stats["dropped_packets"]), 2),
                "bytes_received": self.stats["bytes_received"],
                "subscribed_count": n_subs,
                "inter_packet_ms": ipt_stats,
                "plc_interval_ms": plc_stats,
                "per_variable": per_var,
                "seq_gaps": self._seq_gaps[-20:],
                "seq_step_mode": max(self._seq_step_counts, key=self._seq_step_counts.get) if self._seq_step_counts else 1,
                "grade": self._compute_grade(pkt_rate, self.stats["dropped_packets"], ipt_stats),
            }

    def _calc_timing_stats(self, values: list[float]) -> dict:
        """Calculate min/max/avg/median/stddev/p95/p99 for a list of values."""
        if not values:
            return {}
        n = len(values)
        s = sorted(values)
        avg = sum(s) / n
        variance = sum((x - avg) ** 2 for x in s) / n
        return {
            "count": n,
            "min": round(s[0], 3),
            "max": round(s[-1], 3),
            "avg": round(avg, 3),
            "median": round(s[n // 2], 3),
            "stddev": round(math.sqrt(variance), 3),
            "p95": round(s[int(n * 0.95)], 3) if n >= 20 else None,
            "p99": round(s[int(n * 0.99)], 3) if n >= 100 else None,
        }

    def _get_median_plc_interval(self) -> float:
        """Return median PLC timestamp interval from recent data."""
        ts = list(self._plc_timestamps)
        if len(ts) < 3:
            return 0
        deltas = []
        for i in range(1, min(len(ts), 200)):
            d = ts[i] - ts[i - 1]
            if 0 < d < 10000:
                deltas.append(d)
        if not deltas:
            return 0
        deltas.sort()
        return deltas[len(deltas) // 2]

    def _compute_grade(self, pkt_rate: float, drops: int, ipt: dict) -> dict:
        """Compute overall grade and per-metric grades."""
        grades = {}
        # Packet rate grade (at 10ms interval expect ~100 pkt/s)
        if pkt_rate >= 90:
            grades["packet_rate"] = "EXCELLENT"
        elif pkt_rate >= 50:
            grades["packet_rate"] = "GOOD"
        elif pkt_rate >= 10:
            grades["packet_rate"] = "FAIR"
        else:
            grades["packet_rate"] = "POOR"

        # Drop grade
        if drops == 0:
            grades["integrity"] = "PERFECT"
        elif drops < 5:
            grades["integrity"] = "GOOD"
        elif drops < 50:
            grades["integrity"] = "FAIR"
        else:
            grades["integrity"] = "POOR"

        # Jitter grade (stddev of inter-packet time)
        jitter = ipt.get("stddev", 999)
        if jitter < 2:
            grades["jitter"] = "EXCELLENT"
        elif jitter < 5:
            grades["jitter"] = "GOOD"
        elif jitter < 20:
            grades["jitter"] = "FAIR"
        else:
            grades["jitter"] = "POOR"

        # Overall
        order = {"EXCELLENT": 4, "PERFECT": 4, "GOOD": 3, "FAIR": 2, "POOR": 1}
        worst = min(order.get(g, 0) for g in grades.values())
        rev = {4: "EXCELLENT", 3: "GOOD", 2: "FAIR", 1: "POOR"}
        grades["overall"] = rev.get(worst, "POOR")

        return grades

    # ── Benchmark ────────────────────────────────────────────────
    def start_benchmark(self, duration_s: float = 10.0) -> dict:
        """Start a timed benchmark: collect stats for duration_s seconds."""
        if self._bench_running:
            return {"ok": False, "error": "Benchmark already running"}
        if not self.connected:
            return {"ok": False, "error": "Not connected"}
        self._bench_running = True
        self._bench_done = False
        self._bench_result = None
        self._bench_start = time.perf_counter()
        self._bench_duration = duration_s
        self._bench_packets = 0
        self._bench_var_updates = 0
        self._bench_var_changes = 0
        self._bench_drops = 0
        self._bench_inter_pkt = []
        self._bench_plc_ts = []
        self._bench_per_var_changes = {}
        self._bench_prev_values = {}
        self._bench_last_py_time = 0.0
        self._bench_last_seq = 0
        return {"ok": True, "duration_s": duration_s}

    def _record_benchmark(self, seq: int, timestamp: int, var_updates: dict[int, any],
                          py_time: float, pkt_bytes: int):
        """Called from _decode_packet during benchmark."""
        if not self._bench_running:
            return

        elapsed = py_time - self._bench_start
        if elapsed >= self._bench_duration:
            self._finalize_benchmark()
            return

        self._bench_packets += 1
        self._bench_var_updates += len(var_updates)

        if self._bench_last_py_time > 0:
            dt = (py_time - self._bench_last_py_time) * 1000  # ms
            self._bench_inter_pkt.append(dt)
        self._bench_last_py_time = py_time

        self._bench_plc_ts.append(timestamp)

        # Detect real drops via PLC timestamp gaps (not seq number gaps)
        if self._bench_last_seq > 0 and len(self._bench_plc_ts) > 10:
            ts_gap = timestamp - self._bench_plc_ts[-2] if len(self._bench_plc_ts) >= 2 else 0
            median_int = self._get_median_plc_interval()
            if median_int > 0 and ts_gap > median_int * 2.5:
                missed = round(ts_gap / median_int) - 1
                self._bench_drops += missed
        self._bench_last_seq = seq

        for vid, val in var_updates.items():
            prev = self._bench_prev_values.get(vid)
            if prev is not None and prev != val:
                self._bench_var_changes += 1
                self._bench_per_var_changes[vid] = self._bench_per_var_changes.get(vid, 0) + 1
            self._bench_prev_values[vid] = val

    def _finalize_benchmark(self):
        """Compute benchmark results."""
        self._bench_running = False
        elapsed = time.perf_counter() - self._bench_start
        pkts = self._bench_packets

        ipt_stats = self._calc_timing_stats(self._bench_inter_pkt) if self._bench_inter_pkt else {}

        plc_deltas = []
        ts_list = self._bench_plc_ts
        for i in range(1, len(ts_list)):
            d = ts_list[i] - ts_list[i - 1]
            if 0 < d < 10000:
                plc_deltas.append(d)
        plc_stats = self._calc_timing_stats(plc_deltas) if plc_deltas else {}

        n_subs = len(self.subscribed)
        pkt_rate = pkts / elapsed if elapsed > 0 else 0

        per_var = []
        for vid, cnt in sorted(self._bench_per_var_changes.items(), key=lambda x: -x[1]):
            info = self.registry.get(vid)
            per_var.append({
                "name": info["name"] if info else f"var_{vid}",
                "plc_type": info["plc_type"] if info else "?",
                "changes": cnt,
                "rate": round(cnt / elapsed, 1) if elapsed > 0 else 0,
            })

        # Estimate max safe vars: assume PLC cycle and packet overhead
        # At current rate, each packet carries n_subs vars
        # Network budget ~ bytes_per_pkt * pkt_rate
        avg_bytes_per_var = 9  # ~4 id + 1 type + 4 value avg
        max_pkt_size = 1400  # practical TCP payload
        max_vars_per_pkt = (max_pkt_size - 12) // avg_bytes_per_var
        safe_vars_at_rate = int(max_vars_per_pkt * pkt_rate) if pkt_rate > 0 else 0

        self._bench_result = {
            "elapsed_s": round(elapsed, 2),
            "packets": pkts,
            "packet_rate": round(pkt_rate, 1),
            "var_updates": self._bench_var_updates,
            "var_update_rate": round(self._bench_var_updates / elapsed, 1) if elapsed > 0 else 0,
            "var_changes": self._bench_var_changes,
            "var_change_rate": round(self._bench_var_changes / elapsed, 1) if elapsed > 0 else 0,
            "dropped_packets": self._bench_drops,
            "drop_pct": round(100 * self._bench_drops / max(1, pkts + self._bench_drops), 2),
            "subscribed_count": n_subs,
            "inter_packet_ms": ipt_stats,
            "plc_interval_ms": plc_stats,
            "per_variable": per_var,
            "max_vars_estimate": safe_vars_at_rate,
            "grade": self._compute_grade(pkt_rate, self._bench_drops, ipt_stats),
        }
        self._bench_done = True

    def get_benchmark_status(self) -> dict:
        """Check benchmark progress/results."""
        if self._bench_done and self._bench_result:
            return {"status": "done", "result": self._bench_result}
        if self._bench_running:
            elapsed = time.perf_counter() - self._bench_start
            return {
                "status": "running",
                "elapsed_s": round(elapsed, 1),
                "duration_s": self._bench_duration,
                "packets_so_far": self._bench_packets,
            }
        return {"status": "idle"}
