"""
PLC Variable Monitor — Gateway Engine
Handles TCP connection to PLC for subscription commands and
UDP reception for variable value updates.

Wire protocol: Standard Protocol Buffers (protobuf) binary format.
Schema: proto/plcmonitor.proto

TCP framing: [LENGTH:4B LE][PROTOBUF_BYTES:LENGTH]
UDP: Raw protobuf VarUpdatePacket (no framing needed)
"""

import json
import math
import socket
import struct
import threading
import time
from collections import deque
from pathlib import Path
from typing import Callable

# Import generated protobuf classes
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from proto import plcmonitor_pb2 as pb

# MsgType enum values (from PlcMessage.MsgType)
MSGTYPE_VAR_UPDATE       = 0
MSGTYPE_SUBSCRIBE_CMD    = 1
MSGTYPE_REGISTRY_REQUEST = 2
MSGTYPE_REGISTRY_RESP    = 3
MSGTYPE_HEARTBEAT        = 4
MSGTYPE_CONFIG_CMD       = 5
MSGTYPE_CONFIG_RESPONSE  = 6
MSGTYPE_WRITE_VAR        = 7
MSGTYPE_WRITE_VAR_RESP   = 8

# SubscribeCommand.Action enum values
ACTION_SET    = 0
ACTION_ADD    = 1
ACTION_REMOVE = 2

# TransportMode enum values
TRANSPORT_TCP = 0
TRANSPORT_UDP = 1

TCP_PORT = 55000
UDP_PORT = 55001


class PlcMonitorEngine:
    """Manages PLC connection, subscriptions, and variable data."""

    def __init__(self):
        self.plc_ip: str = ""
        self.connected = False
        self._tcp_sock: socket.socket | None = None
        self._udp_sock: socket.socket | None = None
        self._rx_thread: threading.Thread | None = None
        self._udp_thread: threading.Thread | None = None
        self._running = False
        self._lock = threading.Lock()
        self.transport_mode = TRANSPORT_TCP

        # Variable registry: var_id → {name, plc_type}
        self.registry: dict[int, dict] = {}
        # Reverse map: name → var_id
        self.name_to_id: dict[str, int] = {}
        # Available vars (discovered on PLC): set of var_id that actually exist
        self.available_vars: set[int] = set()
        self._discovery_done = False
        self._discovering = False
        # Current values cache: var_id → value
        self.values: dict[int, any] = {}
        # Per-variable change timestamps: var_id → {plc_ts, py_ts}
        # plc_ts = PLC timestamp in ms (from packet header)
        # py_ts  = Python wall-clock time (time.time()) when change detected
        self.last_changed: dict[int, dict] = {}
        # Active subscription set: set of var_id
        self.subscribed: set[int] = set()
        # Callback for value updates
        self._on_update: Callable | None = None
        # Stats
        self.stats = {
            "packets_received": 0,
            "last_seq": 0,
            "last_timestamp": 0,
            "dropped_packets": 0,
            "bytes_received": 0,
        }
        # Detailed performance stats
        self._stats_lock = threading.Lock()
        self._stats_start_time: float = 0.0
        self._last_packet_py_time: float = 0.0
        self._inter_packet_times: deque[float] = deque(maxlen=10000)
        self._plc_timestamps: deque[int] = deque(maxlen=10000)
        self._per_var_changes: dict[int, int] = {}  # var_id → change count
        self._per_var_prev: dict[int, any] = {}      # var_id → previous value
        self._total_var_updates: int = 0
        self._seq_gaps: list[tuple] = []   # (prev_seq, cur_seq, ts_gap, missed)
        self._seq_step_counts: dict[int, int] = {}  # seq_step → count
        # Benchmark state
        self._bench_running = False
        self._bench_start: float = 0.0
        self._bench_duration: float = 0.0
        self._bench_packets: int = 0
        self._bench_var_updates: int = 0
        self._bench_var_changes: int = 0
        self._bench_drops: int = 0
        self._bench_inter_pkt: list[float] = []
        self._bench_plc_ts: list[int] = []
        self._bench_per_var_changes: dict[int, int] = {}
        self._bench_done = False
        self._bench_result: dict | None = None

    def load_registry(self, registry_path: str | Path | None = None):
        """Load variable registry from JSON file (generated by plc_registry_from_st.py).
        Format: { "plc_index": {"name": "...", "type": "..."}, ... }"""
        if registry_path is None:
            registry_path = Path(__file__).parent.parent / "plc_var_registry.json"

        with open(registry_path) as f:
            raw = json.load(f)

        self.registry.clear()
        self.name_to_id.clear()

        for idx_str, info in raw.items():
            idx = int(idx_str)
            if isinstance(info, dict):
                # New format: {"name": "...", "type": "..."}
                self.registry[idx] = {"name": info["name"], "plc_type": info["type"]}
                self.name_to_id[info["name"]] = idx
            else:
                # Legacy format: name → type (sequential index)
                self.registry[idx] = {"name": idx_str, "plc_type": info}
                self.name_to_id[idx_str] = idx

    def _get_cpu_var_ids(self) -> list[int]:
        """Return var_ids for gMachine.Out.Monitors.Cpu.* variables (always-on profiler)."""
        PREFIX = "gMachine.Out.Monitors.Cpu."
        return [vid for vid, info in self.registry.items()
                if info["name"].startswith(PREFIX)]

    def _iter_visible_vars(self):
        """Iterate over variables visible to the UI.
        If discovery has been done, only yield available vars.
        Otherwise yield all registry vars (pre-discovery fallback)."""
        if self._discovery_done and self.available_vars:
            for var_id in self.available_vars:
                info = self.registry.get(var_id)
                if info:
                    yield var_id, info
        else:
            yield from self.registry.items()

    def get_default_vars(self, prefix: str = "gProtoTest") -> list[dict]:
        """Return all leaf variables under a prefix (for auto-selection)."""
        result = []
        for var_id, info in self._iter_visible_vars():
            name = info["name"]
            if name.startswith(prefix + ".") or name == prefix or (
                "." not in name and name.startswith(prefix)
            ):
                result.append({
                    "id": str(var_id),
                    "name": info["name"],
                    "plc_type": info["plc_type"],
                })
        return result

    def get_tree(self) -> list[dict]:
        """Build a tree structure from flat variable paths for UI browsing."""
        tree = {}
        for var_id, info in self.registry.items():
            parts = info["name"].split(".")
            node = tree
            for i, part in enumerate(parts):
                if part not in node:
                    node[part] = {"_children": {}, "_vars": []}
                if i == len(parts) - 1:
                    node[part]["_vars"].append({
                        "id": var_id,
                        "name": info["name"],
                        "leaf": parts[-1],
                        "plc_type": info["plc_type"],
                    })
                else:
                    node = node[part]["_children"]
        return self._tree_to_list(tree, "")

    def _tree_to_list(self, node: dict, prefix: str) -> list[dict]:
        """Convert nested dict tree to flat list for API."""
        result = []
        for key, val in sorted(node.items()):
            if key.startswith("_"):
                continue
            path = f"{prefix}.{key}" if prefix else key
            children = val.get("_children", {})
            vars_here = val.get("_vars", [])

            if vars_here:
                for v in vars_here:
                    result.append({
                        "id": str(v["id"]),
                        "name": v["leaf"],
                        "full_name": v["name"],
                        "is_variable": True,
                        "has_children": False,
                        "plc_type": v["plc_type"],
                        "value": str(self.values.get(v["id"], "—")),
                    })
            if children:
                result.append({
                    "id": f"folder:{path}",
                    "name": key,
                    "full_name": path,
                    "is_variable": False,
                    "has_children": True,
                })
        return result

    def browse(self, node_id: str | None = None) -> list[dict]:
        """Browse children of a node (for lazy tree loading)."""
        if not self.registry:
            return []

        if node_id is None:
            # Root level — return top-level struct variable names
            roots = {}
            for var_id, info in self._iter_visible_vars():
                top = info["name"].split(".")[0]
                if top not in roots:
                    roots[top] = {"count": 0}
                roots[top]["count"] += 1

            return [
                {
                    "id": f"node:{name}",
                    "name": name,
                    "is_variable": False,
                    "has_children": True,
                    "value": f"({info['count']} fields)",
                }
                for name, info in sorted(roots.items())
            ]

        # Find children of this node
        if node_id.startswith("node:"):
            prefix = node_id[5:]
        elif node_id.startswith("folder:"):
            prefix = node_id[7:]
        else:
            return []

        # Find all vars/folders under this prefix
        children = {}
        for var_id, info in self._iter_visible_vars():
            name = info["name"]
            if not name.startswith(prefix + "."):
                continue
            rest = name[len(prefix) + 1:]
            parts = rest.split(".")
            next_part = parts[0]

            if len(parts) == 1:
                # Leaf variable
                children[f"var:{var_id}"] = {
                    "id": str(var_id),
                    "name": next_part,
                    "full_name": name,
                    "is_variable": True,
                    "has_children": False,
                    "plc_type": info["plc_type"],
                    "value": str(self.values.get(var_id, "—")),
                }
            else:
                # Subfolder
                folder_path = f"{prefix}.{next_part}"
                if folder_path not in children:
                    children[folder_path] = {
                        "id": f"node:{folder_path}",
                        "name": next_part,
                        "is_variable": False,
                        "has_children": True,
                    }

        return list(children.values())

    # ── Connection ───────────────────────────────────────────────
    def connect(self, plc_ip: str, transport: str = "tcp") -> dict:
        """Connect to PLC via TCP (commands + data stream).
        
        Args:
            plc_ip: PLC IP address.
            transport: Preferred transport for variable updates — "tcp" (default) or "udp".
                       TCP is recommended when UDP is blocked by firewall.
                       UDP listener is always opened as fallback for PLC compatibility.
        """
        with self._lock:
            # Always tear down any existing connection first
            if self.connected or self._tcp_sock is not None:
                self.disconnect()

            self.plc_ip = plc_ip
            self.transport_mode = TRANSPORT_TCP if transport.lower() == "tcp" else TRANSPORT_UDP

            # TCP connection for subscription commands and data stream
            try:
                self._tcp_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                self._tcp_sock.settimeout(3.0)
                self._tcp_sock.connect((plc_ip, TCP_PORT))
                self._tcp_sock.settimeout(1.0)
            except Exception as e:
                self._tcp_sock = None
                return {"ok": False, "error": f"TCP connect failed: {e}"}

            self.connected = True
            self._running = True

            # Start TCP receiver thread (handles commands, ACKs, and variable data in TCP mode)
            self._rx_thread = threading.Thread(
                target=self._tcp_receive_loop, daemon=True
            )
            self._rx_thread.start()

            # Tell the PLC which transport to use for variable updates
            self._send_config_command(self.transport_mode)

            # Always open UDP listener as fallback — the PLC may not support
            # CONFIG_CMD yet and still sends variable data over UDP.
            try:
                self._udp_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                self._udp_sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                self._udp_sock.bind(("0.0.0.0", UDP_PORT))
                self._udp_sock.settimeout(1.0)
            except Exception as e:
                print(f"[UDP] Failed to bind port {UDP_PORT}: {e}")
                self._udp_sock = None

            if self._udp_sock:
                self._udp_thread = threading.Thread(
                    target=self._udp_receive_loop, daemon=True
                )
                self._udp_thread.start()

            mode_name = "TCP" if self.transport_mode == TRANSPORT_TCP else "UDP"
            print(f"[CONNECT] Preferred transport: {mode_name} "
                  f"(UDP fallback {'active' if self._udp_sock else 'failed'})")
            return {"ok": True, "url": f"{plc_ip}:{TCP_PORT}", "transport": mode_name}

    def discover_available(self, batch_size: int = 500,
                           batch_wait_s: float = 0.15) -> dict:
        """Discover which variables actually exist on the connected PLC.
        Subscribes in small batches (PLC subscription array is 500 max)
        and collects which var_ids produce data — those have pAddress
        resolved on the PLC."""
        if not self.connected:
            return {"ok": False, "error": "Not connected"}
        if self._discovering:
            return {"ok": False, "error": "Discovery already in progress"}

        self._discovering = True
        self.available_vars.clear()
        self._discovery_done = False

        all_ids = sorted(self.registry.keys())
        if not all_ids:
            self._discovering = False
            return {"ok": False, "error": "Registry is empty"}

        # Set a fast interval for discovery (include empty SET to not disturb subscription)
        self._send_tcp_command(0x01, [], count_override=4)
        time.sleep(0.05)

        # Process in batches — subscribe each batch with SET, wait, collect
        total_batches = (len(all_ids) + batch_size - 1) // batch_size
        for batch_num, i in enumerate(range(0, len(all_ids), batch_size)):
            if not self._running:
                break
            batch = all_ids[i:i + batch_size]
            # SET this batch (replaces previous subscription)
            self._send_tcp_command(0x01, batch)
            # Wait for PLC to respond with data for valid vars in this batch
            time.sleep(batch_wait_s)
            # Collect any var_ids that appeared in values during this window
            self.available_vars.update(self.values.keys())
            # Clear values for next batch
            self.values.clear()
            if (batch_num + 1) % 10 == 0:
                print(f"[DISCOVERY] Batch {batch_num+1}/{total_batches} "
                      f"— found {len(self.available_vars)} so far")

        # After discovery, auto-subscribe to CPU profiler vars
        cpu_ids = self._get_cpu_var_ids()
        if cpu_ids:
            self._send_tcp_command(0x01, cpu_ids)
            self.subscribed = set(cpu_ids)
        else:
            self._send_tcp_command(0x01, [])
            self.subscribed.clear()
        self.values.clear()
        self.last_changed.clear()

        self._discovery_done = True
        self._discovering = False

        print(f"[DISCOVERY] Found {len(self.available_vars)} available variables "
              f"out of {len(self.registry)} in registry")

        return {
            "ok": True,
            "available_count": len(self.available_vars),
            "registry_count": len(self.registry),
        }

    def get_discovery_status(self) -> dict:
        """Return current discovery state."""
        return {
            "done": self._discovery_done,
            "discovering": self._discovering,
            "available_count": len(self.available_vars),
            "registry_count": len(self.registry),
        }

    def disconnect(self) -> dict:
        """Disconnect from PLC."""
        with self._lock:
            self._running = False
            if self._tcp_sock:
                try:
                    self._tcp_sock.close()
                except Exception:
                    pass
                self._tcp_sock = None
            if self._udp_sock:
                try:
                    self._udp_sock.close()
                except Exception:
                    pass
                self._udp_sock = None
            self.connected = False
            self.subscribed.clear()
        return {"ok": True}

    # ── Subscription commands ────────────────────────────────────
    def subscribe(self, var_names: list[str]) -> dict:
        """Subscribe to variables by name. Sends SET command to PLC.
        Always includes CPU profiler variables."""
        var_ids = []
        not_found = []
        for name in var_names:
            if name in self.name_to_id:
                var_ids.append(self.name_to_id[name])
            else:
                not_found.append(name)

        if not var_ids:
            return {"ok": False, "error": "No valid variable names", "not_found": not_found}

        # Always merge CPU profiler vars
        cpu_ids = self._get_cpu_var_ids()
        merged = list(set(var_ids) | set(cpu_ids))
        self.subscribed = set(merged)
        self._send_subscribe_chunked(merged)

        return {
            "ok": True,
            "subscribed": len(var_ids),
            "not_found": not_found,
        }

    def subscribe_by_ids(self, var_ids: list[int]) -> dict:
        """Subscribe by numeric var_ids. Always includes CPU profiler variables."""
        valid = [vid for vid in var_ids if vid in self.registry]
        # Always merge CPU profiler vars
        cpu_ids = self._get_cpu_var_ids()
        merged = list(set(valid) | set(cpu_ids))
        self.subscribed = set(merged)
        self._send_subscribe_chunked(merged)
        return {"ok": True, "subscribed": len(merged)}

    def _send_subscribe_chunked(self, var_ids: list[int], chunk_size: int = 5000):
        """Send subscribe in chunks of chunk_size. First chunk uses SET, rest use ADD."""
        if len(var_ids) <= chunk_size:
            self._send_tcp_command(0x01, var_ids)  # SET
        else:
            for i in range(0, len(var_ids), chunk_size):
                chunk = var_ids[i:i + chunk_size]
                cmd = 0x01 if i == 0 else 0x02  # SET first, ADD rest
                self._send_tcp_command(cmd, chunk)
                if i > 0:
                    import time
                    time.sleep(0.05)  # Small delay between chunks

    def set_interval(self, interval_ms: int) -> dict:
        """Set PLC send interval."""
        interval_ms = max(1, min(10000, interval_ms))
        # Send interval-only change (SET with 0 vars preserves existing subscription)
        self._send_tcp_command(0x01, [], count_override=interval_ms)
        return {"ok": True, "interval_ms": interval_ms}

    def get_profiler_data(self) -> dict:
        """Read PLC CPU profiler variables from the values cache."""
        cpu = {}
        PREFIX = "gMachine.Out.Monitors.Cpu."
        for vid, info in self.registry.items():
            name = info.get("name", "")
            if name.startswith(PREFIX):
                val = self.values.get(vid)
                if val is not None:
                    field = name[len(PREFIX):]
                    cpu[field] = val
        # Structure the output
        return {
            # System-wide idle (from LogIdleShow)
            "sys_idle_rate": cpu.get("SysIdleRate", None),
            "sys_busy_pct": cpu.get("SysBusyPct", None),
            "sys_idle_time_us": cpu.get("SysIdleTimeUs", None),
            "sys_total_time_us": cpu.get("SysTotalTimeUs", None),
            # This task's profiling
            "task_class": cpu.get("TaskClass", None),
            "cycle_time_us": cpu.get("CycleTimeUs", None),
            "exec_time_us": cpu.get("ExecTimeUs", None),
            "idle_time_us": cpu.get("IdleTimeUs", None),
            "load_pct": cpu.get("LoadPct", None),
            "load_avg": cpu.get("LoadAvg", None),
            "load_peak": cpu.get("LoadPeak", None),
            "exec_min_us": cpu.get("ExecMin", None),
            "exec_max_us": cpu.get("ExecMax", None),
            "exec_avg_us": cpu.get("ExecAvgUs", None),
            "total_cycles": cpu.get("TotalCycles", None),
            "overruns": cpu.get("Overruns", None),
            # Configured task class cycle times
            "cycle_times_us": {
                f"Cyclic#{i}": cpu.get(f"Cycle{i}Us", None)
                for i in range(1, 9)
            },
        }

    def _send_tcp_command(self, cmd: int, var_ids: list[int],
                          count_override: int | None = None):
        """Send a protobuf-encoded PlcMessage command to PLC over TCP.
        
        cmd mapping (legacy → protobuf):
          0x01 (SET)       → SubscribeCommand(action=SET, var_ids=...)
          0x02 (ADD)       → SubscribeCommand(action=ADD, var_ids=...)
          0x03 (REMOVE)    → SubscribeCommand(action=REMOVE, var_ids=...)
          0x04 (INTERVAL)  → SubscribeCommand(action=SET, interval_ms=count_override)
          0xFF (HEARTBEAT) → PlcMessage(type=HEARTBEAT)
        """
        if not self._tcp_sock:
            return

        msg = pb.PlcMessage()
        
        if cmd == 0xFF:
            # Heartbeat
            msg.type = MSGTYPE_HEARTBEAT
        else:
            # Subscribe command (SET=0x01, ADD=0x02, REMOVE=0x03)
            msg.type = MSGTYPE_SUBSCRIBE_CMD
            action_map = {0x01: ACTION_SET, 0x02: ACTION_ADD, 0x03: ACTION_REMOVE}
            msg.subscribe.action = action_map.get(cmd, ACTION_SET)
            msg.subscribe.var_ids.extend(var_ids)
            if count_override is not None:
                msg.subscribe.interval_ms = count_override

        # Serialize to protobuf bytes
        pb_bytes = msg.SerializeToString()
        
        # Length-delimited TCP framing: [4B LE length][protobuf bytes]
        frame = struct.pack("<I", len(pb_bytes)) + pb_bytes

        try:
            self._tcp_sock.sendall(frame)
            print(f"[TCP TX] type={msg.type} action={msg.subscribe.action if msg.HasField('subscribe') else '-'} "
                  f"vars={len(var_ids)} frame={len(frame)}B")
        except Exception as e:
            print(f"[TCP TX ERROR] {e}")
            self.connected = False
            try:
                self._tcp_sock.close()
            except Exception:
                pass
            self._tcp_sock = None

    def _send_config_command(self, transport_mode: int):
        """Send a CONFIG_CMD to the PLC to set the transport mode for variable updates."""
        if not self._tcp_sock:
            return

        msg = pb.PlcMessage()
        msg.type = MSGTYPE_CONFIG_CMD
        msg.config_cmd.transport = transport_mode

        pb_bytes = msg.SerializeToString()
        frame = struct.pack("<I", len(pb_bytes)) + pb_bytes

        mode_name = "TCP" if transport_mode == TRANSPORT_TCP else "UDP"
        try:
            self._tcp_sock.sendall(frame)
            print(f"[TCP TX] CONFIG_CMD: transport={mode_name} frame={len(frame)}B")
        except Exception as e:
            print(f"[TCP TX ERROR] Config command failed: {e}")

    def write_var(self, var_name: str, value) -> dict:
        """Write a value to a PLC variable via WRITE_VAR command.
        
        Looks up the var by name, encodes the value as raw LE bytes
        based on the type, and sends a WriteVarCommand message.
        """
        if not self._tcp_sock:
            return {"ok": False, "error": "Not connected"}
        
        if var_name not in self.name_to_id:
            return {"ok": False, "error": f"Unknown variable: {var_name}"}
        
        var_id = self.name_to_id[var_name]
        info = self.registry.get(var_id, {})
        plc_type = info.get("plc_type", "").upper()
        
        # Encode value to little-endian bytes based on PLC type
        if plc_type == "BOOL":
            val_bytes = struct.pack("<B", 1 if value else 0)
        elif plc_type in ("USINT",):
            val_bytes = struct.pack("<B", int(value) & 0xFF)
        elif plc_type in ("SINT",):
            val_bytes = struct.pack("<b", int(value))
        elif plc_type in ("INT",):
            val_bytes = struct.pack("<h", int(value))
        elif plc_type in ("UINT",):
            val_bytes = struct.pack("<H", int(value) & 0xFFFF)
        elif plc_type in ("DINT",):
            val_bytes = struct.pack("<i", int(value))
        elif plc_type in ("UDINT",):
            val_bytes = struct.pack("<I", int(value) & 0xFFFFFFFF)
        elif plc_type in ("REAL",):
            val_bytes = struct.pack("<f", float(value))
        elif plc_type in ("LREAL",):
            val_bytes = struct.pack("<d", float(value))
        else:
            return {"ok": False, "error": f"Unsupported type for write: {plc_type}"}
        
        msg = pb.PlcMessage()
        msg.type = MSGTYPE_WRITE_VAR
        msg.write_var.var_id = var_id
        msg.write_var.value = val_bytes
        
        pb_bytes = msg.SerializeToString()
        frame = struct.pack("<I", len(pb_bytes)) + pb_bytes
        
        try:
            self._tcp_sock.sendall(frame)
            print(f"[TCP TX] WRITE_VAR: {var_name} (id={var_id}) = {value} ({len(val_bytes)}B)")
            return {"ok": True, "var_name": var_name, "var_id": var_id}
        except Exception as e:
            print(f"[TCP TX ERROR] Write var failed: {e}")
            return {"ok": False, "error": str(e)}

    # ── TCP Receiver ─────────────────────────────────────────────
    def _tcp_receive_loop(self):
        """Background thread: receive length-delimited protobuf messages from PLC over TCP."""
        print(f"[TCP RX] Receiver started")
        buf = b""
        _rx_count = 0
        while self._running:
            try:
                chunk = self._tcp_sock.recv(4096)
                if not chunk:
                    print("[TCP RX] Connection closed by PLC")
                    self.connected = False
                    break
                buf += chunk
                _rx_count += 1
                if _rx_count <= 5:
                    print(f"[TCP RX] chunk #{_rx_count}: {len(chunk)}B, buf={len(buf)}B")
                # Process all complete length-delimited messages
                buf = self._process_tcp_buffer(buf)
            except socket.timeout:
                continue
            except OSError as e:
                print(f"[TCP RX] OSError: {e}")
                break
        print("[TCP RX] Thread stopped")

    # ── UDP Receiver ─────────────────────────────────────────────
    def _udp_receive_loop(self):
        """Background thread: receive protobuf VarUpdatePacket from PLC via UDP."""
        print(f"[UDP RX] Receiver started on port {UDP_PORT}")
        while self._running:
            try:
                data, addr = self._udp_sock.recvfrom(1500)
                if data and len(data) >= 2:
                    self._decode_packet(data)
            except socket.timeout:
                continue
            except OSError:
                break
        print("[UDP RX] Thread stopped")

    def _process_tcp_buffer(self, buf: bytes) -> bytes:
        """Extract and decode complete length-delimited protobuf messages.
        TCP framing: [LENGTH:4B LE][PROTOBUF_BYTES:LENGTH]
        Returns the remaining unprocessed bytes."""
        while len(buf) >= 4:
            # Read 4-byte LE length prefix
            msg_len = struct.unpack_from("<I", buf, 0)[0]
            
            # Sanity check
            if msg_len > 65535:
                # Invalid — skip 1 byte and rescan
                buf = buf[1:]
                continue
            
            # Check if full message is available
            if len(buf) < 4 + msg_len:
                break  # Wait for more data
            
            # Extract protobuf bytes
            pb_bytes = buf[4:4 + msg_len]
            buf = buf[4 + msg_len:]
            
            # Decode the PlcMessage
            try:
                msg = pb.PlcMessage()
                msg.ParseFromString(pb_bytes)
                
                if msg.type == MSGTYPE_VAR_UPDATE and msg.HasField('update'):
                    if len(msg.update.values) > 0:
                        self._decode_protobuf_update(msg.update, len(pb_bytes))
                    else:
                        # PLC sends flat VarValues (no submessage wrappers)
                        n = self._decode_flat_update(pb_bytes, len(pb_bytes))
                        if n and not getattr(self, '_flat_logged', False):
                            print(f"[TCP RX] Flat decoder: {n} vars from {len(pb_bytes)}B")
                            self._flat_logged = True
                elif msg.type == MSGTYPE_SUBSCRIBE_CMD:
                    if msg.HasField('subscribe'):
                        print(f"[TCP RX] Subscribe ACK: action={msg.subscribe.action} "
                              f"count={msg.subscribe.interval_ms}")
                elif msg.type == MSGTYPE_HEARTBEAT:
                    if msg.HasField('update'):
                        print(f"[TCP RX] Heartbeat: subs={msg.update.sequence} "
                              f"registry={msg.update.timestamp}")
                elif msg.type == MSGTYPE_CONFIG_RESPONSE:
                    if msg.HasField('config_resp'):
                        self.transport_mode = msg.config_resp.transport
                        mode_name = "TCP" if self.transport_mode == TRANSPORT_TCP else "UDP"
                        print(f"[TCP RX] Config response: transport={mode_name}")
                else:
                    print(f"[TCP RX] Message type={msg.type}")
            except Exception as e:
                # PlcMessage parse failed — try fallback flat decoder
                try:
                    n = self._decode_flat_update(pb_bytes, len(pb_bytes))
                    if n and not getattr(self, '_flat_logged', False):
                        print(f"[TCP RX] Flat decoder (fallback): {n} vars from {len(pb_bytes)}B")
                        self._flat_logged = True
                except Exception as e2:
                    hex_preview = pb_bytes[:32].hex(' ')
                    print(f"[TCP RX] Decode error: {e} | len={msg_len} first32={hex_preview}")

        return buf

    @staticmethod
    def _read_varint(data: bytes, pos: int) -> tuple:
        """Read a varint from data at pos. Returns (value, new_pos)."""
        value = 0
        shift = 0
        while pos < len(data):
            b = data[pos]
            value |= (b & 0x7F) << shift
            shift += 7
            pos += 1
            if (b & 0x80) == 0:
                break
        return value, pos

    def _decode_flat_update(self, pb_bytes: bytes, pkt_bytes: int) -> int:
        """Decode VarUpdatePacket where VarValue fields are flat (no submsg wrappers).
        Returns number of variables decoded, or 0 on failure."""
        # Extract inner VarUpdatePacket from PlcMessage envelope
        pos = 0
        data = pb_bytes
        inner = None
        
        while pos < len(data):
            tag_byte = data[pos]
            field_num = tag_byte >> 3
            wire_type = tag_byte & 0x07
            pos += 1
            
            if wire_type == 0:  # varint
                while pos < len(data) and (data[pos] & 0x80):
                    pos += 1
                pos += 1
            elif wire_type == 2:  # length-delimited
                length, pos = self._read_varint(data, pos)
                if field_num == 2:  # PlcMessage.update
                    inner = data[pos:pos + length]
                    break
                pos += length
            elif wire_type == 5:
                pos += 4
            elif wire_type == 1:
                pos += 8
            else:
                break
        
        if inner is None:
            return 0
        
        # Parse the flat VarUpdatePacket
        pos = 0
        data = inner
        seq = 0
        timestamp = 0
        var_updates = {}
        current_var_id = None
        first_seq = True
        first_ts = True
        
        while pos < len(data):
            tag_byte = data[pos]
            field_num = tag_byte >> 3
            wire_type = tag_byte & 0x07
            pos += 1
            
            if wire_type == 0:  # varint
                value, pos = self._read_varint(data, pos)
                
                if field_num == 1:
                    if first_seq:
                        seq = value
                        first_seq = False
                    else:
                        current_var_id = value
                elif field_num == 2:
                    if first_ts:
                        timestamp = value
                        first_ts = False
                    elif current_var_id is not None:
                        var_updates[current_var_id] = bool(value)
                        current_var_id = None
                elif field_num == 3:
                    if current_var_id is not None:
                        if value > 0x7FFFFFFF:
                            value = value - 0x100000000
                        var_updates[current_var_id] = value
                        current_var_id = None
                elif field_num == 4:
                    if current_var_id is not None:
                        var_updates[current_var_id] = value
                        current_var_id = None
                elif field_num == 5:
                    if current_var_id is not None:
                        if value > 0x7FFFFFFF:
                            value = value - 0x100000000
                        var_updates[current_var_id] = value
                        current_var_id = None
                        
            elif wire_type == 5:  # 32-bit fixed
                if current_var_id is not None and pos + 4 <= len(data):
                    val = struct.unpack_from("<f", data, pos)[0]
                    var_updates[current_var_id] = round(val, 6)
                    current_var_id = None
                pos += 4
                    
            elif wire_type == 1:  # 64-bit fixed
                if current_var_id is not None and pos + 8 <= len(data):
                    val = struct.unpack_from("<d", data, pos)[0]
                    var_updates[current_var_id] = round(val, 9)
                    current_var_id = None
                pos += 8
                    
            elif wire_type == 2:  # length-delimited
                length, pos = self._read_varint(data, pos)
                if field_num == 3:
                    # Properly wrapped VarValue submessage — parse it
                    sub = data[pos:pos + length]
                    vid, val = self._parse_varvalue_sub(sub)
                    if vid is not None:
                        var_updates[vid] = val
                elif current_var_id is not None and field_num == 8:
                    var_updates[current_var_id] = data[pos:pos+length].decode('utf-8', errors='replace')
                    current_var_id = None
                pos += length
            else:
                break
        
        if not var_updates:
            return 0
        
        # Update stats and values (same as _decode_protobuf_update)
        py_now = time.perf_counter()
        with self._stats_lock:
            if self.stats["packets_received"] == 0:
                self._stats_start_time = py_now
            self.stats["last_seq"] = seq
            self.stats["last_timestamp"] = timestamp
            self.stats["packets_received"] += 1
            self.stats["bytes_received"] += pkt_bytes
            if self._last_packet_py_time > 0:
                dt_ms = (py_now - self._last_packet_py_time) * 1000
                self._inter_packet_times.append(dt_ms)
            self._last_packet_py_time = py_now
            self._plc_timestamps.append(timestamp)
        
        updates = {}
        for vid, val in var_updates.items():
            self.values[vid] = val
            info = self.registry.get(vid)
            if info:
                updates[info["name"]] = val
        
        wall_time = time.time()
        with self._stats_lock:
            self._total_var_updates += len(var_updates)
            for vid, val in var_updates.items():
                prev = self._per_var_prev.get(vid)
                if prev is not None and prev != val:
                    self._per_var_changes[vid] = self._per_var_changes.get(vid, 0) + 1
                    self.last_changed[vid] = {"plc_ts": timestamp, "py_ts": wall_time}
                elif prev is None:
                    self.last_changed[vid] = {"plc_ts": timestamp, "py_ts": wall_time}
                self._per_var_prev[vid] = val
        
        if self._bench_running:
            self._record_benchmark(seq, timestamp, var_updates, py_now, pkt_bytes)
        
        if updates and self._on_update:
            self._on_update(timestamp, updates)
        
        return len(var_updates)

    @staticmethod
    def _parse_varvalue_sub(data: bytes) -> tuple:
        """Parse a properly wrapped VarValue submessage. Returns (var_id, value)."""
        pos = 0
        var_id = None
        value = None
        while pos < len(data):
            tag = data[pos]
            field = tag >> 3
            wt = tag & 0x07
            pos += 1
            if wt == 0:
                val = 0
                shift = 0
                while pos < len(data):
                    b = data[pos]
                    val |= (b & 0x7F) << shift
                    shift += 7
                    pos += 1
                    if (b & 0x80) == 0:
                        break
                if field == 1: var_id = val
                elif field == 2: value = bool(val)
                elif field == 3: value = val if val <= 0x7FFFFFFF else val - 0x100000000
                elif field == 4: value = val
                elif field == 5: value = val if val <= 0x7FFFFFFF else val - 0x100000000
            elif wt == 5 and pos + 4 <= len(data):
                val = struct.unpack_from("<f", data, pos)[0]
                pos += 4
                if field == 6: value = round(val, 6)
            elif wt == 1 and pos + 8 <= len(data):
                val = struct.unpack_from("<d", data, pos)[0]
                pos += 8
                if field == 7: value = round(val, 9)
            elif wt == 2:
                length = 0
                shift = 0
                while pos < len(data):
                    b = data[pos]
                    length |= (b & 0x7F) << shift
                    shift += 7
                    pos += 1
                    if (b & 0x80) == 0:
                        break
                if field == 8: value = data[pos:pos+length].decode('utf-8', errors='replace')
                pos += length
            else:
                break
        return var_id, value

    def _decode_packet(self, data: bytes):
        """Decode a protobuf VarUpdatePacket from UDP."""
        if len(data) < 2:
            return

        try:
            update = pb.VarUpdatePacket()
            update.ParseFromString(data)
        except Exception:
            return

        seq = update.sequence
        timestamp = update.timestamp
        count = len(update.values)
        
        if count == 0 and seq == 0:
            return  # Empty/invalid packet

        self._decode_protobuf_update(update, len(data))

    def _decode_protobuf_update(self, update, pkt_bytes: int = 0):
        """Process a decoded VarUpdatePacket protobuf message."""
        seq = update.sequence
        timestamp = update.timestamp
        count = len(update.values)

        py_now = time.perf_counter()

        with self._stats_lock:
            # Stats
            if self.stats["packets_received"] == 0:
                self._stats_start_time = py_now

            prev_seq = self.stats["last_seq"]
            prev_ts = self.stats["last_timestamp"]
            if prev_seq > 0:
                seq_step = seq - prev_seq
                self._seq_step_counts[seq_step] = self._seq_step_counts.get(seq_step, 0) + 1
                if prev_ts > 0 and len(self._plc_timestamps) > 10:
                    ts_gap = timestamp - prev_ts
                    expected_interval = self._get_median_plc_interval()
                    if expected_interval > 0 and ts_gap > expected_interval * 2.5:
                        missed = round(ts_gap / expected_interval) - 1
                        self.stats["dropped_packets"] += missed
                        self._seq_gaps.append((prev_seq, seq, ts_gap, missed))

            self.stats["last_seq"] = seq
            self.stats["seq_step_mode"] = max(self._seq_step_counts, key=self._seq_step_counts.get) if self._seq_step_counts else 1
            self.stats["last_timestamp"] = timestamp
            self.stats["packets_received"] += 1
            self.stats["bytes_received"] += pkt_bytes

            # Inter-packet timing
            if self._last_packet_py_time > 0:
                dt_ms = (py_now - self._last_packet_py_time) * 1000
                self._inter_packet_times.append(dt_ms)
            self._last_packet_py_time = py_now

            # PLC timestamps
            self._plc_timestamps.append(timestamp)

        # Decode variable values from protobuf oneof
        updates = {}
        raw_updates = {}

        for var_val in update.values:
            var_id = var_val.var_id
            value = None
            
            # Extract value from protobuf oneof field
            which = var_val.WhichOneof('value')
            if which == 'bool_val':
                value = var_val.bool_val
            elif which == 'int_val':
                value = var_val.int_val
            elif which == 'uint_val':
                value = var_val.uint_val
            elif which == 'dint_val':
                value = var_val.dint_val
            elif which == 'real_val':
                value = round(var_val.real_val, 6)
            elif which == 'lreal_val':
                value = round(var_val.lreal_val, 9)
            elif which == 'string_val':
                value = var_val.string_val
            
            if value is not None:
                self.values[var_id] = value
                raw_updates[var_id] = value
                info = self.registry.get(var_id)
                if info:
                    updates[info["name"]] = value

        # Track per-variable changes and record change timestamps
        wall_time = time.time()
        with self._stats_lock:
            self._total_var_updates += len(raw_updates)
            for vid, val in raw_updates.items():
                prev = self._per_var_prev.get(vid)
                if prev is not None and prev != val:
                    self._per_var_changes[vid] = self._per_var_changes.get(vid, 0) + 1
                    self.last_changed[vid] = {"plc_ts": timestamp, "py_ts": wall_time}
                elif prev is None:
                    # First time seeing this variable — record initial timestamp
                    self.last_changed[vid] = {"plc_ts": timestamp, "py_ts": wall_time}
                self._per_var_prev[vid] = val

        # Benchmark recording
        if self._bench_running:
            self._record_benchmark(seq, timestamp, raw_updates, py_now, pkt_bytes)

        # Notify callback
        if updates and self._on_update:
            self._on_update(timestamp, updates)

    def set_on_update(self, callback: Callable[[int, dict], None]):
        """Set callback for value updates: callback(timestamp_ms, {name: value})."""
        self._on_update = callback

    # ── Read current values ──────────────────────────────────────
    def read_values(self, names: list[str]) -> dict:
        """Read current cached values for given variable names.
        Returns {name: {value, last_changed_plc_ts, last_changed_py_ts}}."""
        result = {}
        for name in names:
            var_id = self.name_to_id.get(name)
            if var_id is not None:
                entry = {"value": self.values.get(var_id, None)}
                changed = self.last_changed.get(var_id)
                if changed:
                    entry["last_changed_plc_ts"] = changed["plc_ts"]
                    entry["last_changed_py_ts"] = changed["py_ts"]
                result[name] = entry
        return result

    def get_all_values(self) -> dict:
        """Get all currently cached values with change timestamps."""
        result = {}
        for var_id, value in self.values.items():
            info = self.registry.get(var_id)
            if info:
                entry = {"value": value}
                changed = self.last_changed.get(var_id)
                if changed:
                    entry["last_changed_plc_ts"] = changed["plc_ts"]
                    entry["last_changed_py_ts"] = changed["py_ts"]
                result[info["name"]] = entry
        return result

    # ── Search ───────────────────────────────────────────────────
    def search(self, query: str, limit: int = 100) -> list[dict]:
        """Search variable names by substring (only available vars after discovery)."""
        query_lower = query.lower()
        results = []
        for var_id, info in self._iter_visible_vars():
            if query_lower in info["name"].lower():
                results.append({
                    "id": str(var_id),
                    "name": info["name"],
                    "plc_type": info["plc_type"],
                    "value": str(self.values.get(var_id, "—")),
                    "is_variable": True,
                    "has_children": False,
                })
                if len(results) >= limit:
                    break
        return results

    # ── Stats / Benchmark ────────────────────────────────────────
    def reset_stats(self):
        """Reset all live statistics."""
        with self._stats_lock:
            self.stats = {
                "packets_received": 0, "last_seq": 0, "last_timestamp": 0,
                "dropped_packets": 0, "bytes_received": 0,
            }
            self._stats_start_time = time.perf_counter()
            self._last_packet_py_time = 0.0
            self._inter_packet_times.clear()
            self._plc_timestamps.clear()
            self._per_var_changes.clear()
            self._per_var_prev.clear()
            self._total_var_updates = 0
            self._seq_gaps.clear()
            self._seq_step_counts.clear()

    def get_detailed_stats(self) -> dict:
        """Return comprehensive statistics snapshot."""
        with self._stats_lock:
            elapsed = time.perf_counter() - self._stats_start_time if self._stats_start_time else 0
            pkts = self.stats["packets_received"]
            pkt_rate = pkts / elapsed if elapsed > 0 else 0
            var_rate = self._total_var_updates / elapsed if elapsed > 0 else 0

            # Inter-packet timing
            ipt = list(self._inter_packet_times)
            ipt_stats = self._calc_timing_stats(ipt) if ipt else {}

            # PLC timestamp jitter (inter-timestamp deltas)
            plc_ts = list(self._plc_timestamps)
            plc_deltas = []
            for i in range(1, len(plc_ts)):
                d = plc_ts[i] - plc_ts[i - 1]
                if 0 < d < 10000:  # Filter wraps/outliers
                    plc_deltas.append(d)
            plc_stats = self._calc_timing_stats(plc_deltas) if plc_deltas else {}

            # Per-variable change rates (top 30 by change count)
            per_var = []
            for vid, cnt in sorted(self._per_var_changes.items(), key=lambda x: -x[1])[:30]:
                info = self.registry.get(vid)
                per_var.append({
                    "name": info["name"] if info else f"var_{vid}",
                    "plc_type": info["plc_type"] if info else "?",
                    "changes": cnt,
                    "rate": cnt / elapsed if elapsed > 0 else 0,
                })

            total_changes = sum(self._per_var_changes.values())
            n_subs = len(self.subscribed)

            return {
                "elapsed_s": round(elapsed, 1),
                "packets_received": pkts,
                "packet_rate": round(pkt_rate, 1),
                "total_var_updates": self._total_var_updates,
                "var_update_rate": round(var_rate, 1),
                "total_var_changes": total_changes,
                "var_change_rate": round(total_changes / elapsed, 1) if elapsed > 0 else 0,
                "dropped_packets": self.stats["dropped_packets"],
                "drop_pct": round(100 * self.stats["dropped_packets"] / max(1, pkts + self.stats["dropped_packets"]), 2),
                "bytes_received": self.stats["bytes_received"],
                "subscribed_count": n_subs,
                "inter_packet_ms": ipt_stats,
                "plc_interval_ms": plc_stats,
                "per_variable": per_var,
                "seq_gaps": self._seq_gaps[-20:],
                "seq_step_mode": max(self._seq_step_counts, key=self._seq_step_counts.get) if self._seq_step_counts else 1,
                "grade": self._compute_grade(pkt_rate, self.stats["dropped_packets"], ipt_stats),
            }

    def _calc_timing_stats(self, values: list[float]) -> dict:
        """Calculate min/max/avg/median/stddev/p95/p99 for a list of values."""
        if not values:
            return {}
        n = len(values)
        s = sorted(values)
        avg = sum(s) / n
        variance = sum((x - avg) ** 2 for x in s) / n
        return {
            "count": n,
            "min": round(s[0], 3),
            "max": round(s[-1], 3),
            "avg": round(avg, 3),
            "median": round(s[n // 2], 3),
            "stddev": round(math.sqrt(variance), 3),
            "p95": round(s[int(n * 0.95)], 3) if n >= 20 else None,
            "p99": round(s[int(n * 0.99)], 3) if n >= 100 else None,
        }

    def _get_median_plc_interval(self) -> float:
        """Return median PLC timestamp interval from recent data."""
        ts = list(self._plc_timestamps)
        if len(ts) < 3:
            return 0
        deltas = []
        for i in range(1, min(len(ts), 200)):
            d = ts[i] - ts[i - 1]
            if 0 < d < 10000:
                deltas.append(d)
        if not deltas:
            return 0
        deltas.sort()
        return deltas[len(deltas) // 2]

    def _compute_grade(self, pkt_rate: float, drops: int, ipt: dict) -> dict:
        """Compute overall grade and per-metric grades."""
        grades = {}
        # Packet rate grade (at 10ms interval expect ~100 pkt/s)
        if pkt_rate >= 90:
            grades["packet_rate"] = "EXCELLENT"
        elif pkt_rate >= 50:
            grades["packet_rate"] = "GOOD"
        elif pkt_rate >= 10:
            grades["packet_rate"] = "FAIR"
        else:
            grades["packet_rate"] = "POOR"

        # Drop grade
        if drops == 0:
            grades["integrity"] = "PERFECT"
        elif drops < 5:
            grades["integrity"] = "GOOD"
        elif drops < 50:
            grades["integrity"] = "FAIR"
        else:
            grades["integrity"] = "POOR"

        # Jitter grade (stddev of inter-packet time)
        jitter = ipt.get("stddev", 999)
        if jitter < 2:
            grades["jitter"] = "EXCELLENT"
        elif jitter < 5:
            grades["jitter"] = "GOOD"
        elif jitter < 20:
            grades["jitter"] = "FAIR"
        else:
            grades["jitter"] = "POOR"

        # Overall
        order = {"EXCELLENT": 4, "PERFECT": 4, "GOOD": 3, "FAIR": 2, "POOR": 1}
        worst = min(order.get(g, 0) for g in grades.values())
        rev = {4: "EXCELLENT", 3: "GOOD", 2: "FAIR", 1: "POOR"}
        grades["overall"] = rev.get(worst, "POOR")

        return grades

    # ── Benchmark ────────────────────────────────────────────────
    def start_benchmark(self, duration_s: float = 10.0) -> dict:
        """Start a timed benchmark: collect stats for duration_s seconds."""
        if self._bench_running:
            return {"ok": False, "error": "Benchmark already running"}
        if not self.connected:
            return {"ok": False, "error": "Not connected"}
        self._bench_running = True
        self._bench_done = False
        self._bench_result = None
        self._bench_start = time.perf_counter()
        self._bench_duration = duration_s
        self._bench_packets = 0
        self._bench_var_updates = 0
        self._bench_var_changes = 0
        self._bench_drops = 0
        self._bench_inter_pkt = []
        self._bench_plc_ts = []
        self._bench_per_var_changes = {}
        self._bench_prev_values = {}
        self._bench_last_py_time = 0.0
        self._bench_last_seq = 0
        return {"ok": True, "duration_s": duration_s}

    def _record_benchmark(self, seq: int, timestamp: int, var_updates: dict[int, any],
                          py_time: float, pkt_bytes: int):
        """Called from _decode_packet during benchmark."""
        if not self._bench_running:
            return

        elapsed = py_time - self._bench_start
        if elapsed >= self._bench_duration:
            self._finalize_benchmark()
            return

        self._bench_packets += 1
        self._bench_var_updates += len(var_updates)

        if self._bench_last_py_time > 0:
            dt = (py_time - self._bench_last_py_time) * 1000  # ms
            self._bench_inter_pkt.append(dt)
        self._bench_last_py_time = py_time

        self._bench_plc_ts.append(timestamp)

        # Detect real drops via PLC timestamp gaps (not seq number gaps)
        if self._bench_last_seq > 0 and len(self._bench_plc_ts) > 10:
            ts_gap = timestamp - self._bench_plc_ts[-2] if len(self._bench_plc_ts) >= 2 else 0
            median_int = self._get_median_plc_interval()
            if median_int > 0 and ts_gap > median_int * 2.5:
                missed = round(ts_gap / median_int) - 1
                self._bench_drops += missed
        self._bench_last_seq = seq

        for vid, val in var_updates.items():
            prev = self._bench_prev_values.get(vid)
            if prev is not None and prev != val:
                self._bench_var_changes += 1
                self._bench_per_var_changes[vid] = self._bench_per_var_changes.get(vid, 0) + 1
            self._bench_prev_values[vid] = val

    def _finalize_benchmark(self):
        """Compute benchmark results."""
        self._bench_running = False
        elapsed = time.perf_counter() - self._bench_start
        pkts = self._bench_packets

        ipt_stats = self._calc_timing_stats(self._bench_inter_pkt) if self._bench_inter_pkt else {}

        plc_deltas = []
        ts_list = self._bench_plc_ts
        for i in range(1, len(ts_list)):
            d = ts_list[i] - ts_list[i - 1]
            if 0 < d < 10000:
                plc_deltas.append(d)
        plc_stats = self._calc_timing_stats(plc_deltas) if plc_deltas else {}

        n_subs = len(self.subscribed)
        pkt_rate = pkts / elapsed if elapsed > 0 else 0

        per_var = []
        for vid, cnt in sorted(self._bench_per_var_changes.items(), key=lambda x: -x[1]):
            info = self.registry.get(vid)
            per_var.append({
                "name": info["name"] if info else f"var_{vid}",
                "plc_type": info["plc_type"] if info else "?",
                "changes": cnt,
                "rate": round(cnt / elapsed, 1) if elapsed > 0 else 0,
            })

        # Estimate max safe vars: assume PLC cycle and packet overhead
        # At current rate, each packet carries n_subs vars
        # Network budget ~ bytes_per_pkt * pkt_rate
        avg_bytes_per_var = 9  # ~4 id + 1 type + 4 value avg
        max_pkt_size = 1400  # practical TCP payload
        max_vars_per_pkt = (max_pkt_size - 12) // avg_bytes_per_var
        safe_vars_at_rate = int(max_vars_per_pkt * pkt_rate) if pkt_rate > 0 else 0

        self._bench_result = {
            "elapsed_s": round(elapsed, 2),
            "packets": pkts,
            "packet_rate": round(pkt_rate, 1),
            "var_updates": self._bench_var_updates,
            "var_update_rate": round(self._bench_var_updates / elapsed, 1) if elapsed > 0 else 0,
            "var_changes": self._bench_var_changes,
            "var_change_rate": round(self._bench_var_changes / elapsed, 1) if elapsed > 0 else 0,
            "dropped_packets": self._bench_drops,
            "drop_pct": round(100 * self._bench_drops / max(1, pkts + self._bench_drops), 2),
            "subscribed_count": n_subs,
            "inter_packet_ms": ipt_stats,
            "plc_interval_ms": plc_stats,
            "per_variable": per_var,
            "max_vars_estimate": safe_vars_at_rate,
            "grade": self._compute_grade(pkt_rate, self._bench_drops, ipt_stats),
        }
        self._bench_done = True

    def get_benchmark_status(self) -> dict:
        """Check benchmark progress/results."""
        if self._bench_done and self._bench_result:
            return {"status": "done", "result": self._bench_result}
        if self._bench_running:
            elapsed = time.perf_counter() - self._bench_start
            return {
                "status": "running",
                "elapsed_s": round(elapsed, 1),
                "duration_s": self._bench_duration,
                "packets_so_far": self._bench_packets,
            }
        return {"status": "idle"}

    # ── Scaling Stress Test ──────────────────────────────────────
    def run_stress_test(self, levels: list[int] | None = None,
                        step_duration_s: float = 5.0,
                        settle_s: float = 1.0) -> dict:
        """Run progressive stress test: subscribe increasing var counts,
        benchmark each level, return table of results.
        
        Must be called from a background thread (blocks for the full duration).
        """
        if not self.connected:
            return {"ok": False, "error": "Not connected"}

        all_ids = sorted(self.registry.keys())
        max_vars = len(all_ids)

        if levels is None:
            levels = [l for l in [209, 500, 1000, 2000, 5000, 10000, 20000, 50000, max_vars]
                      if l <= max_vars]
            if max_vars not in levels:
                levels.append(max_vars)

        results = []
        self._stress_running = True
        self._stress_progress = {"current_level": 0, "total_levels": len(levels), "results": []}

        for i, count in enumerate(levels):
            if not self._stress_running:
                break

            self._stress_progress["current_level"] = i + 1
            self._stress_progress["current_count"] = count

            # Subscribe to first `count` vars
            ids_subset = all_ids[:count]
            self.subscribed = set(ids_subset)
            self._send_tcp_command(0x01, ids_subset)

            # Let PLC settle with new subscription
            time.sleep(settle_s)

            # Reset stats and run benchmark
            self._bench_running = True
            self._bench_done = False
            self._bench_result = None
            self._bench_start = time.perf_counter()
            self._bench_duration = step_duration_s
            self._bench_packets = 0
            self._bench_var_updates = 0
            self._bench_var_changes = 0
            self._bench_drops = 0
            self._bench_inter_pkt = []
            self._bench_plc_ts = []
            self._bench_per_var_changes = {}
            self._bench_prev_values = {}
            self._bench_last_py_time = 0.0
            self._bench_last_seq = 0

            # Wait for benchmark to complete
            deadline = time.perf_counter() + step_duration_s + 3.0
            while not self._bench_done and time.perf_counter() < deadline:
                time.sleep(0.2)

            if self._bench_result:
                step_result = {
                    "var_count": count,
                    "packet_rate": self._bench_result["packet_rate"],
                    "var_update_rate": self._bench_result["var_update_rate"],
                    "dropped": self._bench_result["dropped_packets"],
                    "drop_pct": self._bench_result["drop_pct"],
                    "inter_pkt_avg_ms": self._bench_result.get("inter_packet_ms", {}).get("avg", 0),
                    "inter_pkt_p99_ms": self._bench_result.get("inter_packet_ms", {}).get("p99", 0),
                    "plc_interval_avg_ms": self._bench_result.get("plc_interval_ms", {}).get("avg", 0),
                    "integrity": self._bench_result.get("grade", {}).get("integrity", "?"),
                    "bytes_per_pkt": round(self._bench_result.get("var_updates", 0) * 9 / max(1, self._bench_result["packets"])),
                }
            else:
                step_result = {
                    "var_count": count,
                    "packet_rate": 0,
                    "var_update_rate": 0,
                    "dropped": -1,
                    "drop_pct": 100,
                    "inter_pkt_avg_ms": 0,
                    "inter_pkt_p99_ms": 0,
                    "plc_interval_avg_ms": 0,
                    "integrity": "FAIL",
                    "bytes_per_pkt": 0,
                }

            results.append(step_result)
            self._stress_progress["results"] = results
            print(f"[STRESS] {count} vars: {step_result['packet_rate']} pkt/s, "
                  f"drops={step_result['dropped']}, integrity={step_result['integrity']}")

        self._stress_running = False

        # Find breaking point: first level with drops > 0
        breaking_point = None
        for r in results:
            if r["dropped"] > 0:
                breaking_point = r["var_count"]
                break

        return {
            "ok": True,
            "levels": results,
            "total_levels": len(results),
            "breaking_point": breaking_point,
            "max_perfect": max((r["var_count"] for r in results if r["dropped"] == 0), default=0),
        }

    def get_stress_progress(self) -> dict:
        if hasattr(self, '_stress_progress'):
            return {
                "running": getattr(self, '_stress_running', False),
                **self._stress_progress,
            }
        return {"running": False}
